### ISSUE TITLE
Next Up scrapes twice if used in home widget

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#39] opened 2022-11-04 19:49 UTC
This looks like it's been around for awhile previously in Kaito [issue #22](https://github.com/SwagOtaku/plugin.video.kaito/issues/22) (2nd to last post in thread) and seems related to [issue 29](https://github.com/Goldenfreddy0703/Otaku/issues/29) here. 

When playing Next Up episodes from a homescreen widget, whether source select or autoplay, it will scrape twice before playing. If using source select, it scrapes, displays the list and when you select the stream, it scrapes and displays the list again. After picking the source a second time it will then play.

I have tried this in both Arctic Horizon 2 and Aeon Nox Silvo (to rule out any widget code issue from a jurielmunkey based skin) and with both anilist and kitsu as watchlist sources.

I see some work has been done lately on Next Up and I was trying to wait and see if the issue got resolved with that, but it looks like it's still there.

Next Up inside the addon works fine, issue is only on home widgets.

**Comment by icpryde** [comment] 2022-11-07 15:16
Their is already an issue open for this very same request #29 so this one can be closed @Goldenfreddy0703

**Comment by icpryde** [comment] 2022-11-07 15:30
@meesterexx a workaround for this for now is to make a widget for “current” from your ani list instead of next up it will then let you into that episode list and form there everything works as intended.

**Comment by meesterexx** [comment] 2022-11-07 15:41
> Their is already an issue open for this very same request #29 so this one can be closed @Goldenfreddy0703

I saw this, and mentioned #29 in my post, but reading through it, I did not see the double scrape mentioned among the issues in that post, which is why I opened this one. That one mentioned no episode info and skip intro function. 

I specifically opened this one so if the issues in #29 got fixed, the double scrape wasn't missed. Feel free to add this symptom to your issue.

**Comment by meesterexx** [comment] 2023-01-23 20:53
Update: I'm not sure exactly when/what changed, but on Kodi 20 with either Arctic Horizon 2 or Auramod, Up Next is no longer double scraping for me, it's acting as expected from widgets. 

@Goldenfreddy0703  BTW, great job on the latest update! You guys continue to impress. Do you have a Donate/Tip link setup anywhere?

**Comment by Goldenfreddy0703** [comment] 2023-01-23 21:25
> Up Next is no longer double scraping for me, it's acting as expected from widgets.
Wait, that's surprising for us to hear, cause i never tested the widgets and thought it was still a bug. Thank you for telling us this, i might test widgets now and all. 

> Do you have a Donate/Tip link setup anywhere?
We do not cause we don't accept tips, we enjoy anime which is why we made this addon possible for everyone to enjoy. 

> @Goldenfreddy0703 BTW, great job on the latest update!
Hey thank you very much, we have been working on this update for weeks and we are so happy to provide this major release. Episode consistency will no longer be a problem anymore.

**Comment by Goldenfreddy0703** [comment] 2023-01-23 21:45
Hey so im going to close this issue and mark it off our todo list but if there by anychance this bug does comeback on special occasion, pls report it to us. 

Thank you

**Closed by Goldenfreddy0703** 2023-01-23 21:45 UTC
Labels: bug, duplicate

**Comment by icpryde** [comment] 2023-01-23 22:51
Yup also noticed it doesn’t double scrap anymore and skip intro doesn’t double anymore but the other issues still persist

**Comment by Goldenfreddy0703** [comment] 2023-01-24 02:38
True
