### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by Rinicko100** [Goldenfreddy0703/Otaku#281] opened 2024-06-14 07:25 UTC
Hello, I noticed the search feature isn't currently working.. Both with the search paths and directly from the add-on, I also tried it on a fork as well as on a different device and received the same results.

**Comment by Goldenfreddy0703** [comment] 2024-06-14 20:47
Hey so from reproducing, it looks like our search is working as well as our custom search paths so my guess is either that Anilist recently had some search issues to take care of or that something could be wrong with your internet so my suggestion is to either look through the troubleshooting steps, unplugging your router and plugging it back in, or check anilist discord server for any updated. 

### Both
`plugin://plugin.video.otaku/search/both/`

### Movies
`plugin://plugin.video.otaku/search/movie/`

### TV Shows
`plugin://plugin.video.otaku/search/show/`

### Troubleshooting
https://github.com/Goldenfreddy0703/Otaku/issues/15

I'm going to go ahead and close this sense i was able to get search working on my end and also that its not a bug on our end.
Thank you

**Closed by Goldenfreddy0703** 2024-06-14 20:47 UTC
