### ISSUE TITLE
Selecting the next episode just plays the same episode again unless I close Kodi.

### ISSUE THREAD

**Issue by Bucchiac** [Goldenfreddy0703/Otaku#309] opened 2024-07-26 10:16 UTC
This is not an issue I ever had in the past. As it is, “Source Select” on an episode now takes ~40 seconds each time to fill up the squares and show the sources. And then I’ll select my source (HD2 seems to be all that works without crashing as far as 1080P goes) and it’ll just start from the beginning of the episode I had just previously watched rather than the next one that I have selected. 

Any idea why this is happening? It’s already such a pain to have to go back into Source Select and wait all of that time again to find sources. If I just let it start playing the next episode or manually skip, it seems to always default to the first source (subbed) even though I’m watching a dub.

**Comment by Goldenfreddy0703** [comment] 2024-07-26 16:02
Ahh this is due to the Aniwave embed again, they decided to tighten there security and it's getting annoying. For now disable aniwave embed in Otakus Provider settings and I think you should be good.

**Comment by Goldenfreddy0703** [comment] 2024-07-26 16:10
> And then I’ll select my source (HD2 seems to be all that works without crashing as far as 1080P goes) and it’ll just start from the beginning of the episode I had just previously watched rather than the next one that I have selected.

Interesting may have to look into that cause it should have picked the next episode for you. Will look into it, thank you

**Comment by joezito129** [comment] 2024-07-27 11:44
for source select you should be able to set a timeout time in the playback settings so you dont have to wait the whole 40 seconds

**Comment by Goldenfreddy0703** [comment] 2024-07-27 18:04
Heyyyy @Bucchiac , from looking at your issues, i looked into it and hopefully it should be fixed and released so hopefully you shouldn't have to go back into Source Select and all and hopefully it should not default to the first source.

Sense your watching dub anime, here is a screenshot that may help you out if you only watch dub anime, these are what my settings are set to in order for me to watch dub anime. As for the Preferred Source Type, you might wanna consider setting that to just dub maybe. 
![image](https://github.com/user-attachments/assets/901c1e3a-420a-4c5a-9ba6-00d7b39bd9af)

I hope this and im going to to go ahead and close this issue, if you have any problems or any issues related to this, please feel free to reply and i will get back to you and look further into this.
Thank you

**Closed by Goldenfreddy0703** 2024-07-27 18:04 UTC

**Comment by chema8132** [comment] 2025-01-24 23:34
Hi there! I'm getting exactly the same issue as is described in the original post, where if I open Otaku, select a serie and episode with source select and play, all the next searches of episodes are useless, as it will just play the first file I chose.

I'll give an example if it can help to figure It out:
 1. Start Kodi (Nvidia SHIELD TV Pro)
 2. Open Otaku addon
 3. Get into Steins Gate anime
 4. Select 1x01 episode with 'select source' option
 5. Choose one of the options and play for a few seconds. Then stop
 6. Select 1x01 episode with 'select source' option once more
 7. Choose any other option (Steins Gate 0 S0E01 for example)
 8. It will just play the previous file (the same as step 5)

From step 5 afterwards it doesnt matter what episode or file you want to play, It will just play the same one all the times. I got the same resulta from Dan da dan anime.

I'll drop the link with the log in case it helps: https://paste.kodi.tv/osuciholoz

As for my Otaku config, I linked Alldebrid account and selected Japanese/Spanish as Dub/Sub preference.

**Comment by Goldenfreddy0703** [comment] 2025-01-25 03:05
Odd it could have something todo with all debrid but not too sure, you may wanna consider trying Otaku testing, its like a better version of Otaku with more fixes and features so hopefully that could fix your issue. Also you may wanna consider clicking on batches or embeds, those will help significantly. 

https://github.com/Goldenfreddy0703/Otaku-Testing

**Comment by chema8132** [comment] 2025-01-25 11:49
Hi! Thanks for the support. I'm currently trying the Otaku Testing version and it looks like the issue is resolved. However, I'm getting so much less results at scraping when compared to Otaku main version. I did some comparison and it looks like the main version get a lot of files from Nyaa, but on the Testing version it dont get any file from that provider. Instead, It only get files from AnimeTosho and Embeds.

**Comment by Goldenfreddy0703** [comment] 2025-01-25 18:35
Yeah I may bring scrapping from the main to testing, you may wanna use embeds just for now
