### ISSUE TITLE
Issues with episodes actually starting since I started using debrid

### ISSUE THREAD

**Issue by lolDayus** [Goldenfreddy0703/Otaku#217] opened 2024-02-17 17:17 UTC
So ever since I started using RD about a week ago, I go in to a series, load up an episode (for some reason this is taking longer as well but whatever), episode load progress bar gets to full, it *acts* like it's about to start the episode (displays flickering etc) but then it just starts loading the next episode as if I had just watched the one it JUST finished loading. This process just repeats over and over until (I assume) the end of the episode list. It definitely says it's using the RD source and RD's site shows the episode was downloaded but the player never actually starts.

So when this happens I've basically just given up and came back later and sometimes it decides to work again and sometimes it doesn't. I've tried clearing out caches and changing RD's "CDN server selection" from Automatic to Cloudflare and then to just Disabled (as I had seen that fixed similar issues for some people) but that might work temporarily and then the next "session" I come back to watch it just does the episode loading loop again. This never happened before I started using RD. What am I missing here?

**Comment by Goldenfreddy0703** [comment] 2024-02-17 19:36
Odd may wanna look onto that, thanks for pointing this out. Try clearing torrent cache if you haven't already.

**Comment by Goldenfreddy0703** [comment] 2024-02-17 22:37
Hey question, would you mind reinstalling Otaku and clearing the appdata and all

**Comment by lolDayus** [comment] 2024-02-18 02:13
yup, still doing it

**Comment by Goldenfreddy0703** [comment] 2024-02-18 03:30
Hey sorry but I forgot to ask, what device are you using and what version of kodi?

**Comment by lolDayus** [comment] 2024-02-18 04:05
I'm on Windows 11 23H2 and Kodi is 21.0-BETA1 (20.90.801)

**Comment by Goldenfreddy0703** [comment] 2024-02-18 05:29
Ahh that could explain alot sense your using Kodi 21.0 Beta 1. We don't really support beta builds just cause something might change in the next beta and all. I did however test on Kodi 21.0 Beta 1 but was not able to reproduce the issue unfortunately but if you can test Otaku on Kodi 19.4 or latest stable version, its possible that the issue your having maybe is kodi related to its beta so see if Otaku on kodi 19.4 works and if it does successfully, this is just a beta issue and we won't have to look into it.

**Comment by Gujal00** [comment] 2024-02-18 19:33
Move to Kodi21Beta3 and see if it improves, I use it on my machine running Win10 22H2 without issues

**Comment by Goldenfreddy0703** [comment] 2024-02-21 18:57
Hey @lolDayus , have you moved to Kodi21Beta3 yet and tested? If you could do that, that would be great so we know if this resolved your issue or not. 

Thank you

**Comment by Goldenfreddy0703** [comment] 2024-04-16 01:15
Heyyy @lolDayus , This issue has been up sense Feb so im gonna go ahead and close this and consider this one fixed sense your the online one having these issues but good news, Kodi 21 recently released which is awesome so give that a try and maybe that will fix your issue. If not feel free to contact me through either discord or keybase and we can work this out. 
Thank you


## Contact

Discord: The Steampunk Owl#3126

Keybase: [Goldenfreddy0703](https://keybase.io/goldenfreddy0703)

**Closed by Goldenfreddy0703** 2024-04-16 01:15 UTC
Labels: bug, Needs Review, Waiting For Response
