### ISSUE TITLE
Nothing is playing in this latest update

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku#374] opened 2024-11-29 19:42 UTC
![image](https://github.com/user-attachments/assets/480b3402-34dd-4fca-8d56-4a8a2cc74989)
https://github.com/user-attachments/assets/1786d984-5266-4ed0-91f4-60474850a79a

**Comment by Gujal00** [comment] 2024-11-30 04:58
No point pasting screenshots, need the full debug log to see what anilist_id was being used which led to this error.
basically `database.get_show(anilist_id)` returned blank and hence the error

**Comment by Goldenfreddy0703** [comment] 2024-11-30 05:13
From looking at the error and video, it looks like it's an anime movie: Black Clover: Sword of the Wizard King

https://anilist.co/anime/131680/Black-Clover-Mahou-Tei-no-Ken

It's when the user is clicking the source inside the source select screen so my guess is that the collect meta is not collecting it properly or something with the resolver from that debrid fix. 

On Otaku Testing, i believe that anime is working fine.

**Comment by Gujal00** [comment] 2024-11-30 05:16
doesnt look like a resolver issue as the failure line on that log is in simkl.py and nothing to do with resolving

**Comment by GitHubSand** [comment] 2024-11-30 09:51
https://paste.kodi.tv/xexamobewu

**Comment by lukefanning** [comment] 2024-12-01 18:49
I can't play any torrent sources since updating to 0.5.35 with RD. I get the following error:

`2024-12-01 18:33:36.777 T:10123   error <general>: 
2024-12-01 18:33:36.778 T:10123   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/debrid/real_debrid.py", line 195, in resolve_single_magnet
                                                       for storage_variant in [hash_]['rd']:
                                                                              ~~~~~~~^^^^^^
                                                   
2024-12-01 18:33:36.778 T:10123   error <general>: 
2024-12-01 18:33:36.778 T:10123   error <general>: TypeError: list indices must be integers or slices, not str`

**Comment by Goldenfreddy0703** [comment] 2024-12-01 19:33
If you don't mind, send us a pr so I can just merge it. Thanks

**Comment by Gujal00** [comment] 2024-12-01 19:54
This was confirmed working here https://github.com/Goldenfreddy0703/Otaku/issues/371#issuecomment-2507501822

Have to see why it doesnt work for you. do not change the code to make it work for you as it may affect others

**Comment by XxSTOZZYxX** [comment] 2024-12-01 20:06
> I can't play any torrent sources (embeds work fine) since updating to 0.5.35 with RD. I get the following error:
> 
> ```
> 2024-12-01 18:33:36.777 T:10123   error <general>: 
> 2024-12-01 18:33:36.778 T:10123   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/debrid/real_debrid.py", line 195, in resolve_single_magnet
>                                                        for storage_variant in [hash_]['rd']:
>                                                                               ~~~~~~~^^^^^^
>                                                    
> 2024-12-01 18:33:36.778 T:10123   error <general>: 
> 2024-12-01 18:33:36.778 T:10123   error <general>: TypeError: list indices must be integers or slices, not str
> ```
> 
> Edit: Fixed it locally by removing the loop `for storage_variant in [hash_]['rd']:` from resolve_single_magnet in real_debrid.py as it appears that the hash is always a single string (presumably since RD API changes). I don't understand how it's only me experiencing this issue.. If you need a PR ping me

i'm getting this same error, but i don't know how to remove the loop on my end to test.

**Comment by XxSTOZZYxX** [comment] 2024-12-01 20:23
@lukefanning pr resolved error on my end

**Closed** 2024-12-03 00:55 UTC
