### ISSUE TITLE
Error going into Next Up (AniList) after upgrade to 0.25

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#16] opened 2022-10-01 15:19 UTC
I get the error:

  File "C:\K19portable\system\python\Lib\genericpath.py", line 152, in _check_arg_types
   raise TypeError(f'{funcname}() argument must be str, bytes, or '
   TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

going into my Next Up section for AniList after upgrading to 0.25. I then install 0.24 over 0.25 and the error goes away and I can access my Next Up. Upgrade again to 0.25 and the error comes back. Did this on 2 different builds (AH2 and Auramod):

Full Error from log:
```
2022-10-01 10:59:51.495 T:13472   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: join() argument must be str, bytes, or os.PathLike object, not 'list'
                                                   Traceback (most recent call last):
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\default.py", line 462, in <module>
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistIntegration.py", line 60, in WATCHLIST_STATUS_TYPE
                                                       return control.draw_items(WatchlistFlavor.watchlist_status_request(flavor, status, params))
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\__init__.py", line 59, in watchlist_status_request
                                                       return WatchlistFlavor.__instance_flavor(name).get_watchlist_status(status, next_up)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\AniList.py", line 166, in get_watchlist_status
                                                       return self._process_status_view(query, variables, next_up, "watchlist/%d", page=1)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\AniList.py", line 216, in _process_status_view
                                                       all_results = list(map(self._base_next_up_view, reversed(entries)))
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\AniList.py", line 400, in _base_next_up_view
                                                       return self._parse_view(base, False)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\WatchlistFlavorBase.py", line 150, in _parse_view
                                                       utils.allocate_item(
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\ui\utils.py", line 10, in allocate_item
                                                       image = os.path.join(control.artPath(), image)
                                                     File "C:\K19portable\system\python\Lib\ntpath.py", line 117, in join
                                                       genericpath._check_arg_types('join', path, *paths)
                                                     File "C:\K19portable\system\python\Lib\genericpath.py", line 152, in _check_arg_types
                                                       raise TypeError(f'{funcname}() argument must be str, bytes, or '
                                                   TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
                                                   -->End of Python script error report<--
                                                   
2022-10-01 10:59:51.630 T:13472    INFO <general>: Python interpreter stopped
2022-10-01 10:59:51.631 T:12600   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.otaku/watchlist_status_type/anilist/CURRENT?next_up=true
2022-10-01 10:59:51.642 T:9800    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_status_type/anilist/CURRENT?next_up=true) failed
```

**Comment by meesterexx** [comment] 2022-10-01 15:20
Forgot to add, I've tried both clear cache & wipe addon data as well. Didn't help the issue.

**Comment by Goldenfreddy0703** [comment] 2022-10-01 15:37
I've actually noticed this yesterday and it could be a watchlist issue or bug, will be fixed soon tho.

**Comment by meesterexx** [comment] 2022-10-01 19:12
I've got it working again in 0.2.5. Looking at the error trace, since Next Up was the only thing not working, I figured it had to be coming from something in WatchlistFlavorBase.py. I diffed the 0.2.4 and 0.2.5 files and the only difference was the 2 lines relating to the function to retrieve fanart:

0.2.4:
show_meta = pickle.loads(show['kodi_meta'])
next_up_meta['image'] = show_meta.get('fanart')

0.2.5:
art = pickle.loads(database.get_show_meta(anilist_id).get('art'))
next_up_meta['image'] = art.get('fanart')


Since I'm not a dev and don't know python, but that was the only difference between the 2 versions, I took a chance and renamed the 0.2.5 WatchlistFlavorBase.py and put the one from 0.2.4 in it's place. That worked, no more error messages and I could access Next Up with the fanart as well. In addition, I did a clear cache and rebuild database after I got it working to be sure it would persist.

**Comment by Gujal00** [comment] 2022-10-02 13:28
`show_meta = pickle.loads(show['kodi_meta'])` should fail in 0.2.5 as the database structure is different

The correct line would be 
`art = pickle.loads(database.get_show_meta(anilist_id)).get('art')` basically ) in the wrong place

**Comment by Gujal00** [comment] 2022-10-02 13:59
@meesterexx The issue is if you reverted to 0.2.4 code you will not get fanart as database structure changed in the new version
The problem is `next_up_meta['image'] = art.get('fanart')` line, it is getting a list of images instead of a single image
It should be `next_up_meta['image'] = random.choice(art.get('fanart'))`
Fix will be in the next release

**Comment by meesterexx** [comment] 2022-10-02 14:44
Thank you! 
What's weird though is some kind of fanart is showing in my Next Up in 0.2.5 with the 0.2.4 file I copied over. Here's my 0.2.5 Next Up:
![screenshot00000](https://user-images.githubusercontent.com/13154733/193459964-0ee32187-b524-4c1d-a0fa-274445ab85ae.png)

**Comment by Goldenfreddy0703** [comment] 2022-10-02 18:05
> Thank you! 
> What's weird though is some kind of fanart is showing in my Next Up in 0.2.5 with the 0.2.4 file I copied over. Here's my 0.2.5 Next Up:
> 

Hey sorry I never replied early but I think the reason why fanart is showing in your Next Up is cause you have already clicked thay anime thay generates fanart when you click into the anime.

**Comment by meesterexx** [comment] 2022-10-02 18:58
> Hey sorry I never replied early but I think the reason why fanart is showing in your Next Up is cause you have already clicked thay anime thay generates fanart when you click into the anime.

That got me thinking so I just tested that theory. I cleared cache and rebuilt database in Otaku, cleared kodi cache and deleted thumbnails folder and disabled my home screen widgets (so they couldn't cache any images before going into Otaku). Then I checked the anilistSync.db to make sure the show meta was empty:

![no_meta](https://user-images.githubusercontent.com/13154733/193471001-058bfedf-22a5-4ed5-9be2-2fd99d59c81f.png)

I went back into kodi and checked the Next Up and it pulled all the fanart again and the show meta table was rebuilt for just the 8 episodes in my Up Next:

![nextup_meta](https://user-images.githubusercontent.com/13154733/193471082-574c59bd-19e9-433a-9f75-ce9938f48316.png)

Could it be the skin pulling the meta? I know auramod uses TMDBHelper for info:
![tmdbh](https://user-images.githubusercontent.com/13154733/193471174-1255d910-2ca1-4c16-8261-9dea9a172718.png)

Not that it matters, I am happy to wait for the official fix, I was just curious where it's getting the art from since the old code is wrong for the new version of Otaku.

**Comment by Goldenfreddy0703** [comment] 2022-10-02 20:08
Oh wait, yes your skin could probably be pulling the meta cause sometimes skins do that especially Auramod but I just realized sense Next Up is just pulling meta of what episode your on and not showing ratings and all, that could be the reason. In not totally sure about next up sense I never use it but I'm sure @Gujal00 knows more about this then me.

**Comment by Goldenfreddy0703** [comment] 2022-10-03 16:32
Hey @meesterexx ,yesterday we released a fix for Nextup and did a couple bug fixes. Go ahead and test out the new release and tell us if your issue has been resolved.

**Comment by meesterexx** [comment] 2022-10-03 16:44
Yes, it's fixed now. Thank you both!

**Comment by Goldenfreddy0703** [comment] 2022-10-03 16:58
Hey anytime!!!

**Closed** 2022-10-03 16:59 UTC
