### ISSUE TITLE
Issues using Otaku add-on 

### ISSUE THREAD

**Issue by Flexxxyyy** [Goldenfreddy0703/Otaku#73] opened 2023-02-09 20:46 UTC
I'm having issues using Otaku add-on. I'm on a firestick 4k max using kodi (20.0). While watching something like about 5 minutes into the show it automatically changes to the next episode of the show.

**Comment by Flexxxyyy** [comment] 2023-02-09 21:21
I'll try the troubleshooting see if that works.

**Comment by Goldenfreddy0703** [comment] 2023-02-10 01:23
Hey @Flexxxyyy , its been a few hours, any luck so far?

**Comment by Flexxxyyy** [comment] 2023-02-10 05:59
> Hey @Flexxxyyy , its been a few hours, any luck so far?

Nah it still keeps happening

**Comment by Flexxxyyy** [comment] 2023-02-10 18:24
I'll take a look at these. I do use NordVPN, but haven't had any issues using other add-ons.

**Comment by Flexxxyyy** [comment] 2023-02-10 18:25
> Hey so your issue is either related to these two post if im correct, you could either be using a vpn or something is wrong with kodi 20.
> 
> https://www.reddit.com/r/Addons4Kodi/comments/z8p2q3/video_playback_randomly_stops_when_streaming_in/
> 
> https://www.reddit.com/r/Addons4Kodi/comments/10y9jkh/playback_stopping_shortly_after_starting/

I'll take a look at these. I do use NordVPN, but haven't had any issues using other add-ons.

**Comment by Goldenfreddy0703** [comment] 2023-02-12 22:20
Heyyyy so im going to close this issue but it is a dupe of issue #69 

Hopefully this issue could get fixed in the next public release of Kodi 21. 

Thank you

**Closed by Goldenfreddy0703** 2023-02-12 22:20 UTC
