### ISSUE TITLE
Playing Next Dialog issue in Arctic Horizon 2 skin

### ISSUE THREAD

**Issue by ShibajiCh** [Goldenfreddy0703/Otaku#67] opened 2023-02-06 15:55 UTC
Hi @Goldenfreddy0703,

Hope you're doing well. After our discussion yesterday regarding the Playing Next Dialog issue via ticket #63 I investigated further and found out that the issue is happening with Arctic Horizon 2 skin which I'm presently using.

What I did was first use the Otaku addon in the default Estuary skin and the Playing Next Dialog appeared fine and also played the next episode correctly. Next I switched back to the Arctic Horizon 2 skin and the Playing Next Dialog appeared fine there too and the next episode played fine too. After this I exited Kodi and opened it again. This is when the issue started happening. The Playing Next Dialog didn't appear in the Arctic Horizon 2 skin this time and the next episode also didn't play. I then switched back to the default Estuary skin again, exited Kodi and opened it again. The Playing Next Dialog appeared fine in the Estuary skin again. So my guess is that when I'm switching to Arctic Horizon 2 skin and exiting Kodi something is happening which is causing the Playing Next Dialog to fail.

I think this issue is similar to ticket #29. I guess you can talk to jurialmunkey the developer of Arctic Horizon 2 skin and try to sort this out, as it is a major Kodi skin at present and many users like me might be facing this issue.

Screenshot in Estuary:

![IMG20230206204755](https://user-images.githubusercontent.com/65297828/217019094-c269f8f8-8275-4744-a458-42334fa768f3.jpg)

Screenshot in Arctic Horizon 2 when it worked without exiting Kodi:

![IMG20230206210542](https://user-images.githubusercontent.com/65297828/217019243-5e7ca957-ba64-4a2a-9550-f6a4703208fd.jpg)

Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-06 16:55
Ok i have been using artic horizon 2 all the time and the Playing Next Dialog works fine for me but i have a few questions to ask. 
Do you have any Otaku widgets setup already in Artic Horizon 2?
If so then could you remove those widets and try the Playing Next Dialog again?
If next dialog does not show, could you restart your kodi?

Answer these questions for me and we can see what to do from here.

**Comment by Goldenfreddy0703** [comment] 2023-02-06 19:36
That is weird, ok by anychance, is there an update maverick build you can try?

**Comment by ShibajiCh** [comment] 2023-02-07 02:36
> Hey sorry i did not get back on your issue but that is weird, ok by anychance, is there an update maverick build you can try?

Hi @Goldenfreddy0703,

I tested it after updating to the latest version of Kodinerds Maven build for Nexus v20. Nevertheless, the same issue is happening. By the way are you on Kodi Nexus or Matrix at present?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-07 02:38
Odd but ok I want you to try something, head to the tools menu in Otaku and Rebuild Database and Wipe Addon Data. After you do that then reconfigure everything then try again.

**Comment by Gujal00** [comment] 2023-02-07 02:42
Nexus or Matrix doesnt matter on Windows as the Python version is locked at 3.8.x for Kodi on Windows.
Android Kodi Nexus got released with Python 3.11.x and that is an issue as there is no way to debug it on Windows platform

Also Kodinerds Maven build is not required anymore as Kodi Omega (v21 Alpha nightly) already uses the latest FFMPEG that supports DV on MKV, the main reason Kodinerds started making a build for Matrix

**Comment by Goldenfreddy0703** [comment] 2023-02-07 03:41
Hey @Gujal00 thanks for pointing this out. @ShibajiCh has been having so many problems with his kodi and with Otaku and we didn't know how and why. It's weird.

**Comment by ShibajiCh** [comment] 2023-02-08 02:53
Hi @Goldenfreddy0703 and @Gujal00,

I installed Kodi Omega official v21 - Alpha 1 and Kodi Omega Fandangos Fork v21 - Alpha 1 on my Nvidia Shield TV Pro and tested with Otaku add-on. Nevertheless, I'm still getting this same issue on those 2 versions as well with Arctic Horizon 2 skin. Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment] 2023-02-08 03:05
Anything above Kodi 19.5 on Android uses Python 3.11.x and there is no way to debug it on other platforms

**Comment by ShibajiCh** [comment] 2023-02-08 03:31
> Anything above Kodi 19.5 on Android uses Python 3.11.x and there is no way to debug it on other platforms

Hi @Gujal00,

Oh okay, then what's the solution? Nexus is much faster compared to Matrix. So what is the plan moving forward for the new Kodi versions?

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment] 2023-02-08 03:57
No solution until either an ubuntu LTS version with python 3.11.x as default ia released or Team_Kodi releases Kodi for Windows with python 3.11.x

**Comment by ShibajiCh** [comment] 2023-02-08 04:06
> No solution until either an ubuntu LTS version with python 3.11.x as default ia released or Team_Kodi releases Kodi for Windows with python 3.11.x

Hi @Gujal00,

Okay, thanks for the information!

@Gujal00 and @Goldenfreddy0703: I tested Otaku on Kodinerds Maven build v19.5 Matrix and can confirm that you were correct. The Playing Next Dialog and the autoplay next episode function are working fine on it. Therefore, the issue is only specific to Nexus and all Kodi versions after that.

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment] 2023-02-08 04:17
The issue is specific to Android  kodi versions nexus and above.
The other platforms such as windows, linux, coreelec, libreelec are all pkay as they do not use python 3.11.x

**Comment by ShibajiCh** [comment] 2023-02-08 06:43
> The issue is specific to Android kodi versions nexus and above. The other platforms such as windows, linux, coreelec, libreelec are all okay as they do not use python 3.11.x on kodi nexus or omega

Hi @Gujal00,

Okay. Thank you! I can understand. Hope some resolution to these issues happen soon. Fingers crossed!

Thanks and Regards,
ShibajiCh.

**Comment by Gujal00** [comment] 2023-02-08 07:03
Okay git the latest CoreElec NE 20.1 nightly which uses python 3.11.1 and there Next up works perfectly fine in Estuary skin. So nothin wrong with Otaku itself running on Python 3.11.1
The issue would be with AH2 skin which cant be solved in Otaku. Please report in @jurialmunky AH2 skin git

**Comment by ShibajiCh** [comment] 2023-02-08 07:48
> Okay got the latest CoreElec NE 20.1 nightly installed which uses python 3.11.1 and there Next up works perfectly fine in Estuary skin. So nothing wrong with Otaku itself running on Python 3.11.1 The issue would be with AH2 skin which cant be solved in Otaku. Please report in @jurialmunky AH2 skin git

Hi @Gujal00,

As per your above instructions I've reported this issue to jurialmunkey here in his GitHub:

https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/806

Let's see what happens.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-08 09:36
Hi @Gujal00 and @Goldenfreddy0703,

Jurialmunkey responded by saying the below:

I dont see how this can be a skin issue. This is not a dialog in the skin. If it comes from the addon then the skin doesn't have any control over it.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 11:25
Hey there, I did not see this as a skin issue in the first place, I do mostly see this as a connection issue tho. We covered the build stuff so it could be due to the connection stuff due to your vpn but again not sure.

**Comment by ShibajiCh** [comment] 2023-02-08 13:11
> Hey there, I did not see this as a skin issue in the first place, I do mostly see this as a connection issue tho. We covered the build stuff so it could be due to the connection stuff due to your vpn but again not sure.

Hi @Goldenfreddy0703,

Thank you, but I'm not sure it's a connection issue or related to my VPN because even without the VPN I'm facing the same issue. Also, if you have followed my earlier replies to @Gujal00 you can see this is Nexus and upward Kodi versions specific and not related to Kodi Matrix. Also, the issue is only happening in the Arctic Horizon 2 skin with only the Otaku addon. All other add-ons like Seren and Fen have perfectly working Playing Next Dialog with Autoplay next episode.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 13:19
Yeah but your the only one having this issue, there is no other user I faced who is having this kind of issue unless.....if @Gujal00 replicated your issue CoreElec NE 20.1 nightly installed which uses python 3.11.1

**Comment by ShibajiCh** [comment] 2023-02-08 13:26
> Yeah but your the only one having this issue, there is no other user I faced who is having this kind of issue unless.....if @Gujal00 replicated your issue CoreElec NE 20.1 nightly installed which uses python 3.11.1

Hi @Goldenfreddy0703,

Like @Gujal00 said in his earlier comments that upto Matrix this issue is not there, and that's true because I copied my exact same .kodi folder to the Matrix version of Kodi and your addon was working perfectly fine with Arctic Horizon 2 skin in it. So definitely that's something. It's only in Nexus and Omega with the new Python version that the issues are happening.

I guess if you could test Otaku on any Android device with Arctic Horizon 2 and Nexus then you see the exact same issue that I'm facing.

Sorry to bother you all so much! However, I really liked Otaku so just trying to make it error free.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 13:28
Oh no, I understand and your not bothering us at all. Ok let me do a test with Linux sense Gujal did CoreElec NE 20.1.

**Comment by ShibajiCh** [comment] 2023-02-08 13:29
Sure @Goldenfreddy0703.
Thank you!

**Comment by ShibajiCh** [comment] 2023-02-08 15:00
> > I guess if you could test Otaku on any Android device with Arctic Horizon 2 and Nexus then you see the exact same issue that I'm facing.
> 
> Actually I did test it on my phone and android TV and Next up appeared fine.

Hi @Goldenfreddy0703,

Then I'm not sure. Nevertheless, how can the exact .kodi folder work on Matrix and not on Nexus, when it's working perfectly fine for you. Don't know.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 15:36
> Then I'm not sure. Nevertheless, how can the exact .kodi folder work on Matrix and not on Nexus, when it's working perfectly fine for you. Don't know.

Im sorry im confused on that, it just works fine for me. Ok i have one idea, what if you deleted or rename your advancedsettings.xml?

Its really easy to do and i can give you the steps for it. 

1. Go to File manager
2. Go to Profile directory Folder
![image](https://user-images.githubusercontent.com/62456796/217575999-b6f6f827-1d80-4912-9422-80d227ed4c3e.png)

3. Delete or rename your advancesettings.xml to something random.
![image](https://user-images.githubusercontent.com/62456796/217576257-62a2c5f5-a034-4db5-ad20-4e1cbc8d8746.png)

4. Restart your kodi and test your next up issue again.

**Comment by ShibajiCh** [comment] 2023-02-08 16:26
> > Then I'm not sure. Nevertheless, how can the exact .kodi folder work on Matrix and not on Nexus, when it's working perfectly fine for you. Don't know.
> 
> Im sorry im confused on that, it just works fine for me. Ok i have one idea, what if you deleted or rename your advancedsettings.xml?
> 
> Its really easy to do and i can give you the steps for it:
> 
> 1. Go to File manager
> 2. Go to Profile directory Folder
>    ![image](https://user-images.githubusercontent.com/62456796/217575999-b6f6f827-1d80-4912-9422-80d227ed4c3e.png)
> 3. Delete or rename your advancesettings.xml to something random.
>    ![image](https://user-images.githubusercontent.com/62456796/217576257-62a2c5f5-a034-4db5-ad20-4e1cbc8d8746.png)
> 4. Restart your kodi and test your next up issue again.

Hi @Goldenfreddy0703,

Sorry but that won't be possible, because I've configured a lot of things in my advancedsettings.xml including the Kodi image path for USB drive where all my images are stored, the cache and buffer size for my playback videos, etc. Moreover, if the issue was with advancedsettings.xml then why would my setup work in Matrix and not in Nexus? Nevertheless, what I'll do is I'll copy my .kodi folder to a separate Kodi Nexus official instance and delete my advancedsettings.xml from it. After testing I'll get back to you shortly on this.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-08 16:56
Hi @Goldenfreddy0703,

I copied my .kodi folder to a separate Kodi Nexus official instance and deleted my advancedsettings.xml from it. After testing the results are same, the issue persists. Working on Estuary and not working on Arctic Horizon 2 after restarting Kodi. I guess there might be some setting in Arctic Horizon 2 which is causing this issue. May be you have it turned off and I have it turned on. This might be specific to Nexus only, hence the issue doesn't happen in Matrix.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 17:17
Ok i took a look at your log again and i noticed something that might have failed that was my fault. I pushed a release and it will be online in 10 min, test it out and tell me if your still having that bug.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 17:42
@ShibajiCh hey sorry again but pushed another quick release, pls test when its released. The release should be online in another 10 min.

**Comment by ShibajiCh** [comment] 2023-02-08 18:36
Hi @Goldenfreddy0703,

Thanks for the updates! However, I'm afraid that the updates didn't fix the Playing Next Dialog issue. Nevertheless, on the positive side I noticed that if I click on "Play from here" through the context menu instead of clicking on the Play button inside video info screen (which I guess is controlled by TMDB Helper), then the Playing Next Dialog appears fine. So is this issue somehow related to the Play button, since "Play from here" works perfectly, or is this issue related to the TMDB Helper addon? I'm not very sure. You might be able to suggest better.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 18:39
Wait which version of Otaku are you using I pushed two releases instead of one.

**Comment by ShibajiCh** [comment] 2023-02-08 18:41
Hi @Goldenfreddy0703,

Further to my above comment, what my observation is that "Play from here" gets the entire list of episodes in the playlist as per my log, whereas the Play button fails to get that. I guess if you can resolve this issue and somehow make the Play button also fetch the entire playlist of episodes then it will solve the widget issue of Playing Next Dialog as well.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-08 18:41
> Wait which version of Otaku are you using I pushed two releases instead of one.

Hi @Goldenfreddy0703,

I'm now using Otaku version 0.3.19

**Comment by Goldenfreddy0703** [comment] 2023-02-08 18:43
Mind sending me another log?

**Comment by ShibajiCh** [comment] 2023-02-08 18:45
> Mind sending me another log?

Hi @Goldenfreddy0703,

Here's my new Kodi log:

https://paste.kodi.tv/maxutuyino

**Comment by Goldenfreddy0703** [comment] 2023-02-08 18:55
> So is this issue somehow related to the Play button, since "Play from here" works perfectly, or is this issue related to the TMDB Helper addon? I'm not very sure. You might be able to suggest better.

Wait were you using the Otaku addon directly or the tmdb helper addon?

**Comment by ShibajiCh** [comment] 2023-02-08 19:13
> > So is this issue somehow related to the Play button, since "Play from here" works perfectly, or is this issue related to the TMDB Helper addon? I'm not very sure. You might be able to suggest better.
> 
> Wait were you using the Otaku addon directly or the tmdb helper addon and did you also restart kodi just incase?
> 
> Btw rebuild database if you could.

Hi @Goldenfreddy0703,

I used Otaku addon directly but I guess the Play button is controlled by TMDB Helper in Arctic Horizon 2 skin, because when I disabled TMDB Helper the Play button in video info screen stopped functioning too. I then used "Play from here" in context menu and the Playing Next Dialog appeared fine. I restarted Kodi, cleared all cache and rebuilt the Otaku database as well before testing, but only "Play from here" displays the Playing Next Dialog and not when played using the normal Play button. I guess this is why the widget issue is also happening because there's no Play from here in widgets.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-08 19:29
Hi @Goldenfreddy0703,

I think this issue with Umbrella addon is similar to Otaku addon issue. Please check below link:

https://github.com/umbrellaplug/umbrellaplug.github.io/issues/201

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 19:42
Possibly sense our playlist is not really fixed yet.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 19:43
Would you mind sending me a new log again.

**Comment by ShibajiCh** [comment] 2023-02-08 19:48
> new

Hi @Goldenfreddy0703,

Sure. Here is my new Kodi log:

https://paste.kodi.tv/ovoxemexem

**Comment by Goldenfreddy0703** [comment] 2023-02-08 21:43
Hey @ShibajiCh , this may not be necessary but is your vpn blocked by rd. 
https://real-debrid.com/vpn

If it is then that could explain alot of things.

**Comment by Goldenfreddy0703** [comment] 2023-02-08 23:53
@ShibajiCh I found out what you kept having these issues and its defiantly the vpn with your rd.

https://twitter.com/RealDebrid/status/1622587338340589568?cxt=HHwWgICz7culy4QtAAAA

**Comment by Goldenfreddy0703** [comment] 2023-02-09 01:08
@ShibajiCh Im sorry but if your still up, pls test this new release cause i made a mistake and i completely was unaware and hopefully Next up will work for you now. Pls test in 10min. 

Thank you

**Comment by ShibajiCh** [comment] 2023-02-09 02:53
Hi @Goldenfreddy0703,

I've updated to Otaku version 0.3.20. I've tested with both NordVPN turned off and on. So we can rule out NordVPN from causing any issues. However, in both cases I've still faced the same issue. Please find my updated Kodi log below in case if you need it:

https://paste.kodi.tv/cigagahupo

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-09 03:21
Ok are you sure you are not using tmdb helper to play Otaku anime?

I really thought that would fix your issue.

**Comment by ShibajiCh** [comment] 2023-02-09 03:29
> Ok are you sure you are not using tmdb helper to play Otaku anime?
> 
> I really thought that would fix your issue.

Hi @Goldenfreddy0703,

I'm playing the anime from inside the Otaku addon and the Play button is inside the video info for every episode. I'm not sure if the Play button works with TMDB Helper because if I disable TMDB Helper then the Play button gets disabled as well, but that is how it works for everything else in Arctic Horizon 2 skin. At this point there is no other Play option available in Arctic Horizon 2 skin apart from "Play from here" in the context menu, which I told you earlier, works fine with the Playing Next Dialog. However, I think this issue is related to why the Playing Next Dialog doesn't work with Otaku widgets, and I think if you can resolve one of these 2 issues then the other will get resolved automatically as well, like it happened in the Umbrella addon thread that I shared.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-09 03:37
Hi @Goldenfreddy0703,

I found a solution. Can we connect on Discord now?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-09 04:57
We have found the fix to the issue, The Default Select action needs to be set to play and not changed. 
![image](https://user-images.githubusercontent.com/62456796/217721966-cc0a087a-9bb0-4d7b-9cb5-b56dbd0d9724.png)

**Closed by Goldenfreddy0703** 2023-02-09 04:57 UTC

**Comment by ShibajiCh** [comment] 2023-02-09 05:39
Thank you @Goldenfreddy0703 !

**Comment by ShibajiCh** [comment] 2023-02-09 06:03
Hi @Goldenfreddy0703,

Please have a look at the below link when you get time. Jurialmunkey has explained how the Play button in the video info screen works and how to overcome it for particular videos like Otaku which doesn't use TMDB ID, as the Play button is completely dependent on the TMDB ID which Otaku doesn't provide and hence it cannot generate the playlist, which is what caused this issue for us in the first place.

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/795

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2023-02-09 09:40
That linked issue is entirely unrelated. AH2 doesn't play anything via TMDbHelper. The TMDbHelper RunScript command is simply used to close out the Recommendations dialog window manager. It doesn't handle any playback.

All playback is handled via the default Kodi builtin function `PlayMedia()` which is called via xbmc.executebuiltin()
i.e `xbmc.executebuiltin('PlayMedia($INFO[ListItem.FileNameAndPath])')`

If FileNameAndPath is empty the skin uses ListItem.FolderPath instead. There is no playback via TMDbHelper.

This is a standard Kodi builtin used for playback.
https://kodi.wiki/view/List_of_built-in_functions#Player_built-in's

**Comment by ShibajiCh** [comment] 2023-02-09 09:53
Hi @jurialmunkey,

Thank you for the detailed explanation!

@Goldenfreddy0703 might be able to look into this.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-09 13:29
Hey guys, so i plan to work on the playlist stuff very soon, it will just take me some time cause its hard to do and idk where to go about that so hopefully if we improve @jkaw branch on the playlist stuff, it will work as it should.

**Comment by ShibajiCh** [comment] 2023-02-09 14:41
> Hey guys, so i plan to work on the playlist stuff very soon, it will just take me some time cause its hard to do and idk where to go about that so hopefully if we improve @jkaw branch on the playlist stuff, it will work as it should.

Hi @Goldenfreddy0703,

Thank you! Hope you find a solution to resolve this playlist issue soon.

Here's my updated log with Arctic Horizon 2 version 0.8.4 in case if you want to refer to it:

https://paste.kodi.tv/docebilogo

Thanks and Regards,
ShibajiCh.
