### ISSUE TITLE
Anilist Watchlist mix matching. Add a check to avoid mixed watchlists/user created lists

### ISSUE THREAD

**Issue by ghost** [Goldenfreddy0703/Otaku#259] opened 2024-05-13 02:39 UTC
I am getting duplicate entries in the anilist section..  it's been like this for a while, so I'm wondering if it's just me or if it's general.

![Screenshot_20240513-031634.png](https://github.com/Goldenfreddy0703/Otaku/assets/169211354/1205b5d5-f456-424f-be60-667dbf4dba2e)

![Screenshot_20240513-032307.png](https://github.com/Goldenfreddy0703/Otaku/assets/169211354/bea12762-e054-410d-a8f3-41931dc40801)

**Comment by Goldenfreddy0703** [comment] 2024-05-13 03:00
Oh you might have messed with the Anime Filter in the Otaku's General settings, The Anime Filter is for animes that are sub and dub and you might have set them to both. Change that to sub or dub if your a dub person.

**Comment by Rinicko** [comment] 2024-05-13 03:03
> Oh you might have messed with the Anime Filter in the Otaku's General settings, The Anime Filter is for animes that are sub and dub and you might have set them to both. Change that to sub or dub if your a dub person. 

I don't have any filters set... the duplicates also only show in completed, paused, and rewatching but are normal in all other sections 🤔

**Comment by Goldenfreddy0703** [comment] 2024-05-13 03:09
> I don't have any filters set... the duplicates also only show in completed, paused, and rewatching but are normal in all other sections 🤔

Interesting, ok try rebuilding database, if that doesn't work then try to reauthenticate the watchlist your using. Also would you mind telling me which watchlist your using?

Thanks

**Comment by Rinicko** [comment] 2024-05-13 03:12
> > I don't have any filters set... the duplicates also only show in completed, paused, and rewatching but are normal in all other sections 🤔
> 
> Interesting, ok try rebuilding database, if that doesn't work then try to reauthenticate the watchlist your using. Also would you mind telling me which watchlist your using?
> 
> Thanks

Okay... Just rebuilt the database. That didn't work. Reauthenticating now

I am using Anilist

**Comment by Rinicko** [comment] 2024-05-13 03:20
> > I don't have any filters set... the duplicates also only show in completed, paused, and rewatching but are normal in all other sections 🤔
> 
> Interesting, ok try rebuilding database, if that doesn't work then try to reauthenticate the watchlist your using. Also would you mind telling me which watchlist your using?
> 
> Thanks

Reauthorization didn't work either... it still comes up with duplicate entries

**Comment by Goldenfreddy0703** [comment] 2024-05-13 03:21
Ok that is the weirdest thing ever, never seen this happen, are you able to go to the anilist website and see if your watchlist is repeating on there?

**Comment by Rinicko** [comment] 2024-05-13 03:25
It's normal on the website

![Screenshot_20240513_042331_Chrome.jpg](https://github.com/Goldenfreddy0703/Otaku/assets/169211354/10ba93e3-e16f-447b-9ea9-1beec3c9cf9c)

**Comment by Goldenfreddy0703** [comment] 2024-05-13 03:31
Ok interesting, ok you may have to reinstall the addon and clear its app date while uninstalling. This mostly fixes almost every issue and it's possible an update could have broken the database or something so that's my best guess. Try that and tell me If your still getting duplicates or not.

**Comment by Rinicko** [comment] 2024-05-13 03:49
> Ok interesting, ok you may have to reinstall the addon and clear its app date while uninstalling. This mostly fixes almost every issue and it's possible an update could have broken the database or something so that's my best guess. Try that and tell me If your still getting duplicates or not. 

I uninstalled and cleared data... restarted kodi, then reinstalled again.... didn't change a single setting, just authorized the Anilist... it still came up with duplicates 🤔🤔

**Comment by Goldenfreddy0703** [comment] 2024-05-13 03:52
Ok that is the weirdest thing ever, do me a small favor and tell me, what kodi version, what Otaku version, and what device and I will look into it and see if I can reproduce the issue.

**Comment by Rinicko** [comment] 2024-05-13 03:55
> Ok that is the weirdest thing ever, do me a small favor and tell me, what kodi version, what Otaku version, and what device and I will look into it and see if I can reproduce the issue. 

Kodi 21
Latest Otaku verion
Nvidia Shield

**Comment by Goldenfreddy0703** [comment] 2024-05-13 04:01
Ok so i tried reproducing it but no luck, could you try sending a kodi log file? Of you could that would be great.

https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by Rinicko** [comment] 2024-05-13 04:32
> Ok so i tried reproducing it but no luck, could you try sending a kodi log file? Of you could that would be great.
> 
> https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

Ohh damnn... does that mean I might be the only person with this problem 🤔

here's my log file https://paste.kodi.tv/etiqesufaw

**Comment by Goldenfreddy0703** [comment] 2024-05-13 04:41
ok so that log really didn't give me any information but i have noticed you have autowidget and that your using another skin, out of curiosity, try going to the default Estuary skin and try Otaku anilist again and see if it could be a skin issue or autowidget issue, surprisingly, yes your the only person with this problem which is very odd.

**Comment by Rinicko** [comment] 2024-05-13 04:47
> ok so that log really didn't give me any information but i have noticed you have autowidget and that your using another skin, out of curiosity, try going to the default Estuary skin and try Otaku anilist again and see if it could be a skin issue or autowidget issue, surprisingly, yes your the only person with this problem which is very odd. 

I have switched skin and also launched the addon from the normal add-on browser... still the same issue.

If I'm the only person with the problem, then I'll rather not bother you anymore... there must've been something I've done, maybe something I'm missing... Anyways, thank you for your time and responses. it is very much appreciated 🙏

**Comment by Goldenfreddy0703** [comment] 2024-05-13 04:53
Feel free to bother me, im always active. Hopefully we can figure out your issue very soon. It could be something with view options or something with your network. Hopefully we will figure it out soon.

**Comment by Rinicko** [comment] 2024-05-13 05:09
> Feel free to bother me, im always active. Hopefully we can figure out your issue very soon. It could be something with view options or something with your network. Hopefully we will figure it out soon. 

I currently don't have to deal with the problem... I added the paths where duplicates show to skin variables filters.. then added "no_label_dupes": "true"... and that has been working for me ever since... It's just a little slower loading up widgets than when I do it directly from the addon. I thought it was a general issue, which was why I brought it up just in case you didn't know about it... The fact that it's just me makes it a strange one.

The only thing I could think of that may be responsible is that I switched from Kitsu to Anilist sometime last year... I can't recall if that was when it started or not, though... plus, it doesn't explain new entries also having duplicates... well, I'll keep trying to think of where it might have stemmed from. If I figure it out, I'll inform you of the cause

**Comment by theasguard** [comment] 2024-05-13 05:15
Tried reproducing your issue since we use anilist also, and are unable to reproduce the issue.

notice a couple things in posted log 
1. install this 'script.skinshortcuts'. should be in the kodi repo
2. check 'AutoWidget' seems to be tossing warnings 
3. The Skin seems to be having issues with the MyVideoNav.xml, specifically invalid entries.

and we'll get you to try 2 things if you dont mind.
1. check your account on anilist, specifically those lists.
2. if you wouldn't mind, uninstall kodi fully restart the device and reinstall kodi, let us know if you figure this out.

**Comment by Rinicko** [comment] 2024-05-13 05:24
> Tried reproducing your issue since we use anilist also, and are unable to reproduce the issue.
> 
> notice a couple things in posted log 
> 1. install this 'script.skinshortcuts'. should be in the kodi repo
> 2. check 'AutoWidget' seems to be tossing warnings 
> 3. The Skin seems to be having issues with the MyVideoNav.xml, specifically invalid entries.
> 
> and we'll get you to try 2 things if you dont mind.
> 1. check your account on anilist, specifically those lists.
> 2. if you wouldn't mind, uninstall kodi fully restart the device and reinstall kodi, let us know if you figure this out.

Thank you for your attempt to recreate the issue... On my anilist, the lists don't show duplicates... I'll try installing the addon on a fork of kodi and seeing if duplicates come up... if it does, then the problem is from my anilist... if it doesn't, then the problem is from my kodi setup

**Comment by Rinicko** [comment] 2024-05-13 05:32
I tried on an entirely different Kodi with no addons or anything installed... default settings, just my anilist added

still got duplicates
 
![Screenshot_20240513-062946.png](https://github.com/Goldenfreddy0703/Otaku/assets/169211354/d3456343-0401-4391-8916-e51faf18883d)

Issue must be from Anilist

**Comment by theasguard** [comment] 2024-05-13 05:37
> > Tried reproducing your issue since we use anilist also, and are unable to reproduce the issue.
> > notice a couple things in posted log
> > 
> > 1. install this 'script.skinshortcuts'. should be in the kodi repo
> > 2. check 'AutoWidget' seems to be tossing warnings
> > 3. The Skin seems to be having issues with the MyVideoNav.xml, specifically invalid entries.
> > 
> > and we'll get you to try 2 things if you dont mind.
> > 
> > 1. check your account on anilist, specifically those lists.
> > 2. if you wouldn't mind, uninstall kodi fully restart the device and reinstall kodi, let us know if you figure this out.
> 
> Thank you for your attempt to recreate the issue... On my anilist, the lists don't show duplicates... I'll try installing the addon on a fork of kodi and seeing if duplicates come up... if it does, then the problem is from my anilist... if it doesn't, then the problem is from my kodi 

 could of duplicated your lists some how and still show as normal on the site. let us know after done said tasks.

also another thing we'll suggest if possible is setting up mal-sync https://malsync.moe  (you can then sync all watchlists, Simkl, kitsu, anilist, mal) then it doesnt limit you to just 1 list.

> I tried on an entirely different Kodi with no addons or anything installed... default settings, just my anilist added
> 
> still got duplicates
> 
> ![Screenshot_20240513-062946.png](https://private-user-images.githubusercontent.com/169211354/329933256-d3456343-0401-4391-8916-e51faf18883d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Nzg2MzYsIm5iZiI6MTcxNTU3ODMzNiwicGF0aCI6Ii8xNjkyMTEzNTQvMzI5OTMzMjU2LWQzNDU2MzQzLTA0MDEtNDM5MS04OTE2LWU1MWZhZjE4ODgzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNTMyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGFkNTM1NGMzNTY2NDg3MzM0ZmZmZjk3ZDhlMDM4ODViMDU1ODY4MDQ1MmVhMDBjZDQ3YmM4ZDI0MThjNzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bp3MlhNm4VSv0Uu187cuBFZZ1DWVObBypy3hT6-jykA)
> 
> Issue must be from Anilist

Anilist could of duplicated your lists some how and it still show as normal on the site, definitely an odd issue.

also another thing we'll suggest if possible is setting up mal-sync https://malsync.moe  (you can then sync all watchlists, Simkl, kitsu, anilist, mal) then it doesnt limit you to just 1 list.
it may also fix that issue for you, without having to go mess around on anilist.

**Comment by Rinicko** [comment] 2024-05-13 05:38
I found the cause.... On my anilist, I have other lists... like after completed, I also created more lists to group the one's I've completed... like completed shonen, completed seinen, completed slice of life e.t.c... It seems the addon is recording all of that, hence why it is under rewatching and completed and 1 item for paused

**Comment by theasguard** [comment] 2024-05-13 05:43
> I found the cause.... On my anilist, I have other lists... like after completed, I also created more lists to group the one's I've completed... like completed shonen, completed seinen, completed slice of life e.t.c... It seems the addon is recording all of that, hence why it is under rewatching and completed and 1 item for paused

okay thats interesting, guess should probably see if can add some kind of check in for user created lists on Anilist to avoid them mix matching.

**Comment by Rinicko** [comment] 2024-05-13 05:43
> 
> Anilist could of duplicated your lists some how and it still show as normal on the site, definitely an odd issue.
> 
> also another thing we'll suggest if possible is setting up mal-sync https://malsync.moe  (you can then sync all watchlists, Simkl, kitsu, anilist, mal) then it doesnt limit you to just 1 list.
> it may also fix that issue for you, without having to go mess around on anilist.

I'll look into malsync... thanks for the suggestion, and also, thanks for your input..

At least now I know the cause, I can handle it better

**Comment by Rinicko** [comment] 2024-05-13 05:46
> > I found the cause.... On my anilist, I have other lists... like after completed, I also created more lists to group the one's I've completed... like completed shonen, completed seinen, completed slice of life e.t.c... It seems the addon is recording all of that, hence why it is under rewatching and completed and 1 item for paused
> 
> okay thats interesting, guess should probably see if can add some kind of check in for user created lists on Anilist to avoid them mix matching.
> 

Yeah, if that is possible... that'll be great 🙏🙏... I really wanted to put that in as a feature request some time back, but it slipped my mind

**Comment by theasguard** [comment] 2024-05-13 05:48
> > Anilist could of duplicated your lists some how and it still show as normal on the site, definitely an odd issue.
> > also another thing we'll suggest if possible is setting up mal-sync https://malsync.moe  (you can then sync all watchlists, Simkl, kitsu, anilist, mal) then it doesnt limit you to just 1 list.
> > it may also fix that issue for you, without having to go mess around on anilist.
> 
> I'll look into malsync... thanks for the suggestion, and also, thanks for your input..
> 
> At least now I know the cause, I can handle it better

no worries, we're here to help with stuff, glad could finally nail down the culprit, and that should help find a resolution for that bug.

**Comment by theasguard** [comment] 2024-05-13 05:54
i updated the Title, labeled it a bug and added the label enhancement, will look into this more.

**Comment by Rinicko** [comment] 2024-05-13 05:55
> i updated the Title, labeled it a bug and added the label enhancement, will look into this more.
> 

Many thanks 🙏

**Comment by Goldenfreddy0703** [comment] 2024-06-09 07:11
Hey so good news, @joezito129 was able to fix the issue with Anilist Watchlist having duplicates, we provided a fix and we should have release out. Im gonna go ahead and close this issue but if more issues occur related to this or if you have more questions, feel free to reply and we will get back to you. 

Thank you

**Closed by Goldenfreddy0703** 2024-06-09 07:11 UTC
Labels: Completed
