### ISSUE TITLE
episode titles don't work on embeds 

### ISSUE THREAD

**Issue by unicornsandcandies** [Goldenfreddy0703/Otaku#25] opened 2022-10-12 21:15 UTC
When I watch episode on kodi from nyaa everything is okay, but when I watch from embeds, then instead of title there's a number like 0 or 1. Sometimes it's just an episode number. I would like it to be title like the rest because that way my trakt addon is scrobbling this and I don't have to do that manually

**Comment by Goldenfreddy0703** [comment] 2022-10-12 22:08
Hey there, im a little confused on what you mean. 
![image](https://user-images.githubusercontent.com/62456796/195457046-0547eaf1-6622-485d-bb01-4ebe9415e624.png)
Are you saying you just want it to be the episode title so that the trakt addon can scrobble it for you?

**Comment by unicornsandcandies** [comment] 2022-10-12 23:13
![otaku](https://user-images.githubusercontent.com/112720004/195464519-20070f13-7fe3-457b-97b1-6a82b52fa528.png)
see? there's no title and no scrobbling

**Comment by Goldenfreddy0703** [comment] 2022-10-12 23:14
ahh i see what you mean now, maybe we can apply a fix on that in a later release soon.

**Comment by Gujal00** [comment] 2022-10-13 00:37
It depends where the meta came from, nit about embed or nyaa, if trakt cant find the series, otaku gets meta from simkl and thats all it will show unfortunately.
Anime is not english, so asking for trakt scrobbling is not possible all the time. If you want scrobbling for anime get a free anilist.co accountand link it to otaku, it will work perfectly on showing whats up mext, mark stuff watched automatically etc.

**Comment by Goldenfreddy0703** [comment] 2022-10-13 02:13
That is true cause trakt can't handle anime that well, I mean sure we could change that 1 in that picture to the anime but again, it depends where the meta has come from like @Gujal00 said.

**Comment by joezito129** [comment] 2022-10-13 02:29
It looks like the problem only occurs when source select option is used.

**Comment by Gujal00** [comment] 2022-10-13 04:03
> ![otaku](https://user-images.githubusercontent.com/112720004/195464519-20070f13-7fe3-457b-97b1-6a82b52fa528.png) see? there's no title and no scrobbling

Can you give the Anime name so that it can tested. Thanks

**Comment by unicornsandcandies** [comment] 2022-10-13 06:43
> > ![otaku](https://user-images.githubusercontent.com/112720004/195464519-20070f13-7fe3-457b-97b1-6a82b52fa528.png) see? there's no title and no scrobbling
> 
> Can you give the Anime name so that it can tested. Thanks

This is chainsaw men. It happens on nyaa but it's more rare (for example Jojo and Spy x Family can be scrobbled). If it works try selecting embed source. 

To answer joezito - no, this happens to me without selecting a source. I'm just more sure that will happen with embeds so this one time I've selected. To present an issue. For this anime a title doesn't work with nyaa sources too, but sometimes this way (for me) it works and sometimes not, so I've picked this option.

Can't there be option for Otaku to take episode name from selected episode? When I'm searching for anime and picking episode, there are titles working, so why wouldn't it work on the player? Or like a trakt integration in addon or something? It's kinda hard for me to have different sites for tracking, I just want trakt because there's a lot of animes anyway

**Comment by unicornsandcandies** [comment] 2022-10-13 06:44
Chainsaw men is on trakt. Every anime that I've had this issue with is on trakt

**Comment by Gujal00** [comment] 2022-10-13 10:05
@unicornsandcandies It may be an issue with the skin you are using
This is on Estuary, the default kodi skin, and is working correctly
![screenshot00000](https://user-images.githubusercontent.com/17394059/195567902-14bf2ddf-9543-42aa-9f23-920d4834fecd.png)
![screenshot00004](https://user-images.githubusercontent.com/17394059/195568179-2470df4a-7f3f-4c32-a065-ce338a636dfe.png)
![screenshot00001](https://user-images.githubusercontent.com/17394059/195568249-9918b109-0947-4c55-8d9d-ce1f939612d7.png)

**Comment by Gujal00** [comment] 2022-10-13 20:02
> It's kinda hard for me to have different sites for tracking, I just want trakt because there's a lot of animes anyway

The problem is if you want anime, you have to use anime-centric scrobbler. Trakt uses TMDB for episode meta. TMDB treats anime as if American TV series with annual seasons and epsiodes.
There are no seasons in Anime, each season if any is a new show and some times a show is split into to two parts and each part starts with episode 1-12(or 13). This makes trakt/tmdb meta usesless when scraping for a source from anime sites as they follow show name numbering as the anime studios number them
You can nice meta if we use trakt/tmdb but you wont get any playable sources if you follow their numbering scheme. There are many examples such as SpyxFamily Part1 and 2, Mushoku Tensei Part1 and 2 etc.

So if your anime works with trakt scrobbling, it is just a bonus, you cant expect it to work for everything

**Comment by Goldenfreddy0703** [comment] 2022-10-14 01:04
Hey so im going to close this issue but you guys did help me notice a bug that needs fixing soon so thank you guys

**Closed by Goldenfreddy0703** 2022-10-14 01:04 UTC

**Comment by Goldenfreddy0703** [comment] 2022-10-14 02:58
@unicornsandcandies funny story, it looks like it was a Context Menu Select Source bug this whole time. Thank you for posting this issue and it will be fixed in our next release. Now one thing to keep note of: Trakt will not always scrobble what you watch on anime but it Anilist, Mal, Kitsu will always keep track. 

Thank you
