### ISSUE TITLE
Can't watch TV Shows, Only Movies

### ISSUE THREAD

**Issue by OKSoda** [Goldenfreddy0703/Otaku#188] opened 2023-12-20 22:18 UTC
Hey there

Fresh install of Otaku on a fresh Kodi Install. 

I can successfully see sources from movies in Otaku but when I try to browse shows, whenever I select a show I get an error in Kodi. Here is what the logo shows

```
2023-12-20 17:11:59.488 T:1908    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 21, in <module>
                                                       main.Main()
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 731, in ANIMES_PAGE
                                                       anime_general, content = _BROWSER.get_anime_init(anilist_id, filter_lang)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 109, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\indexers\simkl.py", line 174, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\indexers\simkl.py", line 96, in _process_episode_view
                                                       s_id = utils.get_season(sync_data[0])
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2023-12-20 17:11:59.635 T:5304    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.otaku/animes/154587/52991/0
2023-12-20 17:11:59.644 T:15444   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/animes/154587/52991/0) failed
2023-12-20 17:12:00.010 T:15444    info <general>: Loading skin file: C:\Users\joeyw\AppData\Roaming\Kodi\addons\script.logviewer\resources\skins\Default\720p\script.logviewer-textwindow-fullscreen.xml, load type: LOAD_ON_GUI_INIT
2023-12-20 17:12:00.010 T:15444 warning <general>: Skin has invalid include: Animation_DialogPopupOpenClose
2023-12-20 17:12:18.469 T:19408   error <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/Wit Studio.png
2023-12-20 17:12:20.902 T:11392   error <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/Frontier Works.png
2023-12-20 17:12:38.484 T:11392   error <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/Wit Studio.png
2023-12-20 17:12:45.384 T:14708   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 21, in <module>
                                                       main.Main()
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 731, in ANIMES_PAGE
                                                       anime_general, content = _BROWSER.get_anime_init(anilist_id, filter_lang)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 109, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\indexers\simkl.py", line 174, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                     File "C:\Users\joeyw\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\indexers\simkl.py", line 96, in _process_episode_view
                                                       s_id = utils.get_season(sync_data[0])
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
```

I've tried everything i can think of, reinstalling, clearing cache etc. LMK what else to try! Thanks.

**Comment by Goldenfreddy0703** [comment] 2023-12-20 22:44
Ok weird, 2 other people had this issue and I did as well this morning. Idk if it's a connection issue or a debrid issue. I tried finding the cause or source of it but was not able to find it. I will have someone look into this.

Thank you.

**Comment by OKSoda** [comment] 2023-12-20 22:45
Slightly comforting knowing im not alone. Thanks for the quick response!

**Comment by joezito129** [comment] 2023-12-21 00:35
it looks like syncurl (ie. https://find-my-anime.dtimur.de/api) stopped working.

**Comment by joezito129** [comment] 2023-12-21 00:46
if you want a quick fix change line 96 of simkl.py to s_id = [-1]
This should let you watch the show but will show season# as -1.

**Comment by Goldenfreddy0703** [comment] 2023-12-21 01:44
Alright so apparently some idiot around 5 hours, abused the api which is why went down. Hopefully it will be back up soon. 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/ad6e4ccc-a66f-4e4d-a119-4ec4762570fb)

**Comment by OKSoda** [comment] 2023-12-21 02:29
Ok, sounds good. Will keep an eye on it.

**Comment by Goldenfreddy0703** [comment] 2023-12-21 04:07
Hey so good news, we got it fixed and i added a fallback. @joezito129 about that quick fixed you mentioned, I did this instead "s_id = utils.get_season(sync_data[0]) if sync_data else None" cause i think the find-my-anime will come back online very soon. 

Release should be out so @OKSoda hopefully this should fix your issue. Will go ahead and close this but if issues still occur, please message in here and we will open this and look further. 

Thank you

**Closed by Goldenfreddy0703** 2023-12-21 04:07 UTC
Labels: bug, fixed
