### ISSUE TITLE
[issue] AniList delayed metadata syncing for Current menu

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#143] opened 2023-08-12 15:48 UTC
Okay, here's the issue. I had noticed over the past few months an issue with the **Current** menu section when navigating the AniList in particular, I haven't tried with MAL or any other of the available Anime trackers. 

The issue consist of whenever I new Episode of a currently watching show is Aired it will pop out instantly in the **Next Up** menu section. However, if you go into the **Current** section that Episode will not be there. Like if there's a delay or bug when syncing from AniList to Otaku. Next Up is instant, same as when you watch an Episode it will mark it instantly as watched in AniList. However Data from AniList to Otaku in the **Current** menu section requires you to always manually do a **Rebuild Database** in order for the **Current** menu to present the updated content from any TV Show that has aired a new episode recently, etc. 

Here's some screenshots showing you an example of the issue. This is **Bleach: Thousand-Year Blood War - The Separation** which just aired it's 6th Episode and when I got the AniList notification 🔔 and checked in Otaku, it was instantly available in the **Next Up** Menu. Where as, checking into the **Current** menu which is basically "Currently TV Shows in progress" and you go into the TV Show title, open the Season and as you will see int the screenshots below it doesn't sync and stays showing Episode 5 as the latest indefinitely, until you do a manual **Rebuild Database**. 

I mean, it's kind of annoying as you have to be doing this multiple times which can take a toll I believe with the servers, etc. Hopefully you can look into this and see if there's a solution which this menu section can start syncing instantly from AniList same as the **Next Up** menu, and others. 

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/f19f83f7-7681-47e2-9218-955de3ce3441)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/3d03d712-43ca-49d8-b507-618fc35b23a3)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/3a97f454-b012-4c3f-a949-3903689f8e13)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/e4bd35c9-9db6-427d-b591-a0e3538f81c2)

Edited: This happens with all the Shows that are in the **Current** menu, specially if the Season is currently airing and new episodes are released on a weekly basis.

**Comment by Goldenfreddy0703** [comment] 2023-08-12 20:52
Ok i kinda see see what you mean but at the same time, i don't but i do understand that episode meta does not update due to not checking the episode database for it so i can understand that part and me and @joezito129 have a plan for it. For the next up, im kinda lost on that cause next up is quite complicated and possibly buggy and i kinda wanna do a recode on it to be like serens next up in the future.

**Comment by Gujal00** [comment] 2023-08-12 22:42
`Next UP`  in Anilist has got nothing to do with next up at the end of playback.
Anilist `Next UP` works perfectly as intended.
The issue with episode meta is that consumet/enime were not providing airdates, so no way to know when to resync the databaae. Recently looks like @joezito129 has done some work with airdates, so any currently airing show with airdates should get updated, and if not needs to be looked at

**Comment by Nuklear92** [comment] 2023-08-12 23:28
> Ok i kinda see see what you mean but at the same time, i don't but i do understand that episode meta does not update due to not checking the episode database for it so i can understand that part and me and @joezito129 have a plan for it. For the next up, im kinda lost on that cause next up is quite complicated and possibly buggy and i kinda wanna do a recode on it to be like serens next up in the future. 

Yeah, the **Next Up** menu as you can see gets synced instantly from AniList when any of my in progress TV shows airs a new Episode if the Season is on-going. However, the issue seems to be with the menu called **Current**. That menus is the one that doesn't get synced and you have manually do a **Rebuild Database** in order for the TV Show to reflect the latest airing Episode.

**Comment by joezito129** [comment] 2023-08-12 23:32
This issue is the same as #137 we are currently working on it.

**Comment by Goldenfreddy0703** [comment] 2023-08-13 06:59
Hey @Nuklear92 , we just made a release that should fix the AniList delayed metadata syncing for Current menu and that should update whenever a new episodes come out. Pls feel free to test our new release and if this release works perfectly for you, pls close this issue unless you still have problems.

**Comment by Nuklear92** [comment] 2023-08-13 14:42
> Hey @Nuklear92 , we just made a release that should fix the AniList delayed metadata syncing for Current menu and that should update whenever a new episodes come out. Pls feel free to test our new release and if this release works perfectly for you, pls close this issue unless you still have problems. 

So far it's working great after the update, I'll keep an eye on it. Specially when a new episode airs from one of the shows I'm watching and double check on the **Current** menu without doing any Database Rebuilds, hopefully it will update metadata instantly like the **Next Up** menu section does. 👍

I'll go ahead and close the issue for now.

Also, sorry this is a bit out of topic but I'll go ahead and ask it here just to hear if there's any plans or status on this.

Had you guys @Goldenfreddy0703 @Gujal00 @joezito129 thought about adding support for Easynews as a provider. I don't know if you're aware or not but there's a nice small community of Anime content uploaders there, and believe or not I've seen a lot of super high quality BluRay links from Movies, tv show season, and they're quite active uploading good copies of newly released Episodes of popular shows and other shows that aren't even too popular. But, the link quality are very good a lot coming from AMZN video with Dolby Audio and good bitrate, and other copies uploaded from Nyaa and other sources of Anime content. Some of these links on older tv shows or seasons, movies that had been finished or out from a long time and as you may or may not know. Debrid Services tend to do clean outs from their servers when particular links that had been cached, but haven't been watched in a long time. So, you need to manually cache this files again by uploading on the Debrid services. The issue is, when some of this links, files are a bit too old, they start losing trackers, peers, etc. So, it becomes harder for them to get downloaded from torrent tools or in the case of debrid service. There's a lot of old gems and entire season of older shows in BluRay quality that I've seen on easynews, that aren't even cached on Debrid services anymore or simply if you wanna cache them, they barely have any trackers, available for the file to download completely.

**Closed** 2023-08-13 14:43 UTC
Labels: Needs Review, Waiting For Response

**Comment by Goldenfreddy0703** [comment] 2023-08-13 22:49
uhhh, you kinda lost me there with your long paragraph with Easynews. I have thought about supporting Easynews but non of our contributors have used Easynews and we don't know how to add it. It is on our todo list tho but it will take some time to add and to learn about as well. Hopefully we will add it someday.
