### ISSUE TITLE
[Bug] Scraping with Cloud Storage option ON and manual Batch selection ON issue

### ISSUE THREAD

**Issue by Nuklear92** [Goldenfreddy0703/Otaku#169] opened 2023-10-31 00:32 UTC
Okay, so I have my account with RD with the option to additionally scrape cloud storage in case I have a season pack saved for easy access.

Having the option for manual file selection for Batch torrents, will cause the **Inspect Cloud Files on Scrape** option to pop up a manual selection for the Episodes on the Season pack it finds on my RD cloud storage. However, it will only show one single random episode from the season pack instead of all of the episodes with the Season Pack.

I'll show screenshots below in chronological order so you can see the issue clearly.

![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/4b9bc701-d593-442d-92a0-1b1a59a5ba5e)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/04818c10-7323-4d35-849a-7fb9ad5af81d)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/073a5961-13ea-41c6-bedd-74c55e1bcdf0)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/5173e7e8-f409-4953-b514-bcdab20ae56a)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/3ebce939-41c8-4bcb-a35a-d90d824c46ef)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/76958541/d069bc8e-8b23-47dc-bfa3-b13e438b058e)

As you can see from the screenshots in order. I selected Episode one for scraping, however it only shows one single random episode from the whole season pack **Episode 5** to be specific. 

The correct way it should be, showing the whole season pack and then I manually select the correct episode that matches the episode I'm scraping from the season which in this case is Episode 1. The problem happens with any episode, doesn't matter if it's 1,2,3, etc. just by having the Manual Batch selection ON and also having the Scrape files from cloud storage will always give this inaccurate results. Plus, never showing the whole season pack and just one single random episode from it.

**Comment by joezito129** [comment] 2023-11-02 02:13
I just pushed a fix for this let me know if it is fixed.

**Comment by Goldenfreddy0703** [comment] 2023-11-02 04:41
Heyyyy @Nuklear92, joezito has pushed a fix and we have made a release so go ahead and test that and tell us if this issue is fixed from your side. Im going to close this but if you have any questions, feel free to reply to us in this issue and we will respond and if this issue is not fixed, we will look further into it. 

Thank you

**Comment by Nuklear92** [comment] 2023-11-02 14:41
Yes! It's working perfectly now. Appreciate the time and work spent into fixing this issue. 💙

**Comment by Nuklear92** [comment] 2023-11-04 14:48
@joezito129 @Goldenfreddy0703 Bad news guys. So, I've tried different season packs and they all showing all the episodes now. However, when I click on any of the episodes from the pack it will not play. I'll post a small clip showing the issue in action. 

Hopefully, this is just an easy bug and you guys can get it working correctly. 👍

https://streamable.com/1117wd

**Comment by Goldenfreddy0703** [comment] 2023-11-04 14:56
Hey @Nuklear92 from replicating the issue, it seems to work fine for me, There is a possible chance you may want to rebuild database, clear cache, and clear torrent cache, and restart kodi. Try that and see if you get the same result, also try a different batch torrent or something.

**Comment by Nuklear92** [comment] 2023-11-04 14:57
@Goldenfreddy0703 tried all of those options before doing that clip and that was my result. 😥

**Comment by Nuklear92** [comment] 2023-11-04 14:58
I'll, try maybe reinstalling the addon completely and see if i get the same result. I'll report back in a bit.

**Comment by Goldenfreddy0703** [comment] 2023-11-04 15:04
For a workaround, have change the Movies or Episode Play Style to Auto Play until we have a fix for this.

**Comment by Goldenfreddy0703** [comment] 2023-11-04 15:06
> I'll, try maybe reinstalling the addon completely and see if i get the same result. I'll report back in a bit.

Made a quick edit, you don't have to do those steps. 

Edit: Nevermind it happens when you have select source enabled. Will need to fix that.

To Replicate the Issue, you need these specific settings enabled
Playback > Movie Play Style > Source Select
Playback > Episode Play Style > Source Select
Playback > Terminate Cloud Sources > True
Sort & Filter > Enabled Manual File Selection for Batch Torrents > True

**Comment by Goldenfreddy0703** [comment] 2023-11-04 15:07
For a workaround, have change the Movies or Episode Play Style to Auto Play until we have a fix for this.

**Comment by Nuklear92** [comment] 2023-11-04 15:15
@Goldenfreddy0703 Just for reference I just finished reinstalling the addon and setting up everything completely, and still having the same result. So, there's definitely an issue going on that needs to be patch in order for manual selection to play the episodes successfully from Season Packs.

Edited: Tried your settings and got the same negative results.

**Comment by Goldenfreddy0703** [comment] 2023-11-04 16:22
@Nuklear92 i sent you like a few things and made edits if you check the previous github messages. 

Things i explained in my previous github messages:
 - You did not have to do those steps
 
 - I have replicated the issues and found out that this is caused by playing an episode with Source Select and having Manual File Selection for Batch Torrents turned on
 
> Edited: Tried your settings and got the same negative results.
- Those were settings on how to replicate the issue, you did not have to follow them at all

Workaround: 
Change from Source Select to Auto Play in your Playback Settings

Things I found when testing:
- Terminate on Cloud - Does not have anything to do with it
- Enabled Manual File Selection for Batch Torrents - Defiantly has something to do with Cloud Batch Sources for some odd reason
- When its getting Sources and it gets a Cloud source, it will automatically activate the get_best_match function
- This only happens when you play an episode with Source Select and having Manual File Selection for Batch Torrents turned on

Summary: We have to make it where the Get Sources does not activate the get_best_match function when its getting Cloud Sources

**Comment by Nuklear92** [comment] 2023-11-04 16:40
I see, well I'll just wait then until you guys make it work the correct way when having Playback: Source Select + manual batch selection + cloud source scraping ON. Just give me a mention and I'll try testing again to confirm it's working. 👍

I usually not a fan of having Auto Play because it's not always accurate to the specific files I like to play when it comes to resolution, audio tracks, etc Specially when there are a variety of them available.

**Comment by Nuklear92** [comment] 2023-11-04 16:40
I see, well I'll just wait then until you guys make it work the correct way when having Playback: Source Select + manual batch selection + cloud source scraping ON. Just give me a mention and I'll try testing again to confirm it's working. 👍

I usually not a fan of having Auto Play because it's not always accurate to the specific files I like to play when it comes to resolution, audio tracks, etc Specially when there are a variety of them available.

**Comment by Goldenfreddy0703** [comment] 2023-11-04 20:00
@Nuklear92 good news, me and @joezito129 came up with a fix for this so hopefully this will fix your issue. If you encounter any problems feel free to reply in here and we will look further into it. 

Please tell us if this fixed your issue cause i feel confident that it is fixed.

**Closed by Goldenfreddy0703** 2023-11-04 20:00 UTC
Labels: bug, Workaround, In-Progress

**Comment by Nuklear92** [comment] 2023-11-04 20:45
@Goldenfreddy0703 @joezito129 Yes! Now is working correctly. However, the difference seems to be it now bypasses the source scraping screen and the season pack will appear on top of the list. From there I just click on the pack and it will show all of the Episodes and when I click on the one that matches the show episode I'm scrapping it now plays correctly. 

So, pretty much seems like a better fix of not popping up the season pack in the middle of the scrapping screen process, and instead wait until the scraping is done and you select from the Source Select UI, instead. 👍

Thanks a lot guys for the quick fix! 💙

**Comment by Goldenfreddy0703** [comment] 2023-11-04 21:20
> However, the difference seems to be it now bypasses the source scraping screen and the season pack will appear on top of the list. From there I just click on the pack and it will show all of the Episodes and when I click on the one that matches the show episode I'm scrapping it now plays correctly.

Exactly, that's how it should do it instead of having the user select multiple times and having it show up during the getting sources screen. Glad it works, I was very confident that this would fix it, and also make it better. Huge thanks to @joezito129 for making this possible and improving on this.

**Comment by Nuklear92** [comment] 2023-11-04 21:53
@Goldenfreddy0703 Definitely! This way seems more stable and correct. 😃

Thanks a lot to @joezito129 for the work and dedication being put into making this addon better and better. 💙
