### ISSUE TITLE
Otaku Errors after recent updates

### ISSUE THREAD

**Issue by ShibajiCh** [Goldenfreddy0703/Otaku#63] opened 2023-02-04 19:54 UTC
Hi @Goldenfreddy0703  and @Gujal00,

After the recent last few updates I noticed several issues with Otaku. They are as follows:

1) As soon as any video is played after scraping, immediately Otaku Error notification appears on screen.
2) Episodes/Movies are not getting marked as watched in Anilist.
3) Rescrape and normal scrape results are different.
4) Next up window not appearing at the end of an episode.
5) Cache 0% issue while rewinding or forwarding (without using VPN).
6) Title and summary not appearing on player OSD.

These issues are happening both within the addon and from widget as well. I'm seeing these issues when I'm connected to NordVPN (as Nyaa doesn't work without VPN due to my ISP). I'm using Kodi Nexus v20 on Nvidia Shield TV Pro. My Kodi log is as follows:

https://paste.kodi.tv/edapuwepul

Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 20:32
Hey so if your a Verizon user and your isp does not allow Nyaa, we have an option for specifically Verizon users and we hope that helps you out. 
![image](https://user-images.githubusercontent.com/62456796/216788256-8ca0bfbf-6d31-4bf7-a9ab-9fada995494f.png)

1. Im not sure why but just incase, may need to clear cache, clear torrent cache, rebuild database, and possibly wipe addon data. 
![image](https://user-images.githubusercontent.com/62456796/216788351-dde4737b-5431-4d40-b1b0-11c26180b464.png)

2. You may have to reauthenticate your watchlist again.
![image](https://user-images.githubusercontent.com/62456796/216788384-0fb2fd2f-6ae1-4a46-993f-85096cd9fbce.png)
 
3. That has been a known problem and we plan to take that out someday.

4. That could be a widget issue cause we are still having widget bugs.

5. Some anime embeds could be slow, Example Gogo, sometime Animepehe.

6. Differently a widget bug or possibly a watchlist bug with next up. 

Nvidia Shield TV's have been problems for kodi for some odd reason cause multiple people have been using kodi on that device.

**Comment by ShibajiCh** [comment] 2023-02-04 20:53
Hi @Goldenfreddy0703,

I've already tried all the troubleshooting steps but still I'm getting the Otaku error at the start of every video playback. This issue started happening either after yesterday or today's update. I'm on VPN so Nyaa is working fine for me now. I've re-authenticated Anilist as well. Please check the Kodi error log that I shared earlier, there are a few errors with Otaku that I can see. Could you please check and advise?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:15
Im sorry but i have to ask, how did you install this kodi apk? I see kodinerds mentioned in the appdata part of kodi and i have a feeling that could be the issue from looks at your kodi install information.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:18
The log shows:

- General warnings about deprecated methods of setting video properties in the Kodi API
- Seren, a Kodi addon, performing various actions
- Errors in loading images and accessing files (e.g. "Direct texture file loading failed")
- Loading of skin files and opening of video files in the Kodi media center
- Errors in getting playlist items, accessing directories, and playing videos
- An exception thrown with the message "array out of bound".

These log entries suggest that the software may be encountering issues with the functionality of various addons and the playback of media.

**Comment by ShibajiCh** [comment] 2023-02-04 21:21
Hi @Goldenfreddy0703,

Yes, I'm using Kodinerds Maven build to get Dolby Vision. However, I didn't face these issues before today on the same build. These issues started happening from today only. Also, like I said the issues are mainly happening when I'm connected to VPN. The VPN solves the Nyaa problem but I'm getting the error at the start of every video playback. Turning off the VPN temporarily resolves the error but then I won't be able to access the Nyaa links. Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:28
Ok so its the VPN then. Ok well without the VPN, can you access this site? 

https://nyaa.iss.ink/
Yes or no

**Comment by ShibajiCh** [comment] 2023-02-04 21:28
Hi @Goldenfreddy0703,

What are these errors about?


2023-02-05 01:14:20.542 T:22161    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/get_sources.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 01:14:27.485 T:22161    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/source_select.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 01:14:32.071 T:22161    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/resolver.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 01:14:35.228 T:24689   error <general>: EXCEPTION: array out of bound
2023-02-05 01:14:39.036 T:22161    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.otaku/play/16498/2/
2023-02-05 01:14:39.041 T:24765    info <general>: Creating InputStream
2023-02-05 01:14:39.087 T:24689   error <general>: EXCEPTION: array out of bound
2023-02-05 01:14:40.334 T:24765    info <general>: Creating Demuxer
2023-02-05 01:14:44.292 T:24765    info <general>: Opening stream: 0 source: 256
2023-02-05 01:14:44.293 T:24765    info <general>: Creating video codec with codec id: 173
2023-02-05 01:14:44.293 T:24765    info <general>: CBitstreamConverter::Open bitstream to annexb init
2023-02-05 01:14:44.312 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.mp2.decoder
2023-02-05 01:14:44.320 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.wma.decoder
2023-02-05 01:14:44.320 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.h264.decode
2023-02-05 01:14:44.321 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.DOVI.decode
2023-02-05 01:14:44.321 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.h263.decode
2023-02-05 01:14:44.321 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.h265.decode
2023-02-05 01:14:44.926 T:24765    info <general>: CDVDVideoCodecAndroidMediaCodec:: Open Android MediaCodec OMX.Nvidia.h265.decode
2023-02-05 01:14:44.926 T:24765    info <general>: Creating video thread
2023-02-05 01:14:44.931 T:24791    info <general>: running thread: video_thread
2023-02-05 01:14:44.937 T:24765    info <general>: Opening stream: 2 source: 256
2023-02-05 01:14:44.937 T:24765    info <general>: Finding audio codec for: 86076
2023-02-05 01:14:44.937 T:24765    info <general>: CDVDAudioCodecAndroidMediaCodec: Unknown hints.codec(86076)
2023-02-05 01:14:44.938 T:24765    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
2023-02-05 01:14:44.938 T:24765    info <general>: Creating audio thread
2023-02-05 01:14:44.939 T:24792    info <general>: running thread: CVideoPlayerAudio::Process()
2023-02-05 01:14:44.939 T:24765    info <general>: Opening stream: 3 source: 256
2023-02-05 01:14:44.939 T:24765    info <general>: CDVDSubtitlesLibass: Using libass version 1502000
2023-02-05 01:14:44.939 T:24765    info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2023-02-05 01:14:44.939 T:24765    info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2023-02-05 01:14:44.962 T:24765    info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2023-02-05 01:14:45.010 T:24689   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: 'Eng' is not in list
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/default.py", line 1725, in <module>
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/default.py", line 1655, in PLAY
                                                       player.play_source(link,
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/player.py", line 309, in play_source
                                                       watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang)
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/player.py", line 60, in handle_player
                                                       self.keepAlive()
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/player.py", line 152, in keepAlive
                                                       audio_int = audio_lang.index(preferred_audio)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   ValueError: 'Eng' is not in list
                                                   -->End of Python script error report<--

**Comment by ShibajiCh** [comment] 2023-02-04 21:29
> Ok so its the VPN then. Ok well without the VPN, can you access this site?
> 
> https://nyaa.iss.ink/ Yes or no

Yes this site is accessible without VPN.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:30
These log messages appear to be from a Kodi-based media player running on an Android device. The messages show that the player is loading skin files, attempting to play a video file, and initializing codecs for video and audio playback. The errors "array out of bound" indicate that there is an issue accessing an array that is beyond the valid bounds of its index, which could potentially cause a crash or unexpected behavior.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:31
> > Ok so its the VPN then. Ok well without the VPN, can you access this site?
> > https://nyaa.iss.ink/ Yes or no
> 
> Yes this site is accessible without VPN.

Ok then enable Nyaa Alt on Otaku and don't use the vpn and that should resolve your issue. 
![image](https://user-images.githubusercontent.com/62456796/216790396-502b2472-1a91-4c0b-989b-13f790c19699.png)

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:32
I still don't understand the skin files thing in your log cause it could be due to the kodi nerds build that you have.

**Comment by ShibajiCh** [comment] 2023-02-04 21:35
> > > Ok so its the VPN then. Ok well without the VPN, can you access this site?
> > > https://nyaa.iss.ink/ Yes or no
> > 
> > 
> > Yes this site is accessible without VPN.
> 
> Ok then enable Nyaa Alt on Otaku and don't use the vpn and that should resolve your issue. ![image](https://user-images.githubusercontent.com/62456796/216790396-502b2472-1a91-4c0b-989b-13f790c19699.png)

Hi @Goldenfreddy0703,

Even though the site is accessible I'm not able to get any links from Nyaa Alt without the VPN. That's the reason I've been using the VPN. However, since yesterday or today's update I'm getting the Otaku error while using the VPN. 🙁
Don't know what to do.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-04 21:37
Nevertheless, why will the VPN cause issues suddenly when it's working for everything else perfectly fine? Any ideas?

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:40
Not really sure, maybe the vpn can't really access other stuff or it could mainly be due to your kodi build cause your build is from kodinerds so yeah.

**Comment by ShibajiCh** [comment] 2023-02-04 21:54
> build

Hi @Goldenfreddy0703,

I checked further. Both Nyaa and Nyaa Alt links are not appearing without VPN. Nyaa links are throwing the error with VPN. Other links are working fine with VPN. So it's definitely an issue with the Nyaa links and not the VPN. The Nyaa links are playing fine with VPN but they are throwing the error at the start of playback and after that the progress is not recorded in Anilist.
I'm out of ideas now. At least I can say that the issue is with Nyaa and not the VPN.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 21:57
Ok Thats weird cause when i asked if you could open https://nyaa.iss.ink without the vpn, you said yes but apparently your isp is very strict, wait i should have asked this. 

Did you reconfigure your debrid account?
![image](https://user-images.githubusercontent.com/62456796/216791197-6a5d7b77-80dc-41b3-8b55-75b9bd0b7753.png)

**Comment by ShibajiCh** [comment] 2023-02-04 22:01
Hi @Goldenfreddy0703,

Yes, I uninstalled and reinstalled Otaku and then reconfigured Real Debrid. Still I'm not able to access the Nyaa Alt links without VPN, even though the site is opening without VPN. The Nyaa links are playing fine on VPN but the error is appearing at the beginning of every playback and the progress is not getting recorded in Anilist. For all other non-Nyaa links the progress is recording fine on Anilist while using VPN or not using VPN.
In other add-ons like Seren and Fen the Nyaa links are opening fine without throwing any error.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:22
OK well your VPN is weird tbh and im honestly confused, only thing i can think of at this point is either your kodi build or that there are some api's you can't access or something cause im generally confused. You said you tried all the troubleshooting steps, you cleared cache, cleared torrent cache rebuild database, reconfigured your debrid, re-authenticate your watchlist, enabled Nyaa Alt. 

Ok my team is going to look into it but just incase one last thing to ask sense you get a playback error. Is your watchlist set to update anil;ist?

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:27
Wait a sec, does this happen with a specific anime or all anime?

**Comment by joezito129** [comment] 2023-02-04 22:29
it has to do with the audio lang. Eng and Jpn need to be lowercase

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:29
> it has to do with the audio lang. Eng and Jpn need to be lowercase

I just noticed that and im dumb......and just tested

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:30
Welp ok i should have not capitalized eng in settings last time when i was doing some testing with the settings improvements and i feel dumb......

**Comment by ShibajiCh** [comment] 2023-02-04 22:30
Okay, so are you going to fix it now? I can test. 🙂

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:31
> Okay, so are you going to fix it now? I can test. 🙂

Yes i will defientlly fix cause i should have looked closer in your log then being way too blind to see it.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:32
Im sorry for taking too much of your time, i will have that fixed right now.

**Comment by ShibajiCh** [comment] 2023-02-04 22:35
> Im sorry for taking too much of your time, i will have that fixed right now.

Hi @Goldenfreddy0703,

No problem..at least we found the issue. 🙂
Glad to help you. I too noticed the language error hence I sent you the piece of log separately, but since I'm not such a great Python expert so couldn't pinpoint the issue, but I have knowledge in other programming languages like PHP, so could guess that something fishy was going on with that part of the log. Thank you so much for finding the issue! I'll wait for the update.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:41
Aghhhh i feel stupid, @ShibajiCh im sorry for pinging you but would you mind making a pr and fixing this for me. Your probably faster then me tbh. 😅

**Comment by Goldenfreddy0703** [comment] 2023-02-04 22:41
Aghhhh i feel stupid, @joezito129  im sorry for pinging you but would you mind making a pr and fixing this for me. Your probably faster then me tbh. 😅

**Comment by joezito129** [comment] 2023-02-04 22:47
Ya, no problem

**Comment by Goldenfreddy0703** [comment] 2023-02-04 23:18
Hey so it should be released in a few min. Im going to close this issue but @ShibajiCh pls test for us and tell us if you receive any more errors. 

Thank you,

**Closed by Goldenfreddy0703** 2023-02-04 23:18 UTC

**Comment by ShibajiCh** [comment] 2023-02-04 23:31
> Hey so it should be released in a few min. Im going to close this issue but @ShibajiCh pls test for us and tell us if you receive any more errors.
> 
> Thank you

Hi @Goldenfreddy0703 and @joezito129,

Thank you both for the quick resolution! The error notification has been resolved after the language fix. Episodes and Movies are getting marked as watched on Anilist correctly. However, the Next Up pop up window is still not appearing even in the addon. Nevertheless, I guess that's another issue you can look into later on. Just wanted to let you know my observation.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-04 23:37
> Playing Next Dialog pop up window is still not appearing at the end of the video even if played from within the addon.

Did you by anychance use the context menu or play it normally.

**Comment by ShibajiCh** [comment] 2023-02-04 23:53
> > Playing Next Dialog pop up window is still not appearing at the end of the video even if played from within the addon.
> 
> Did you by anychance use the context menu or play it normally.

I played it normally then fast forwarded upto a few mins before the end of the video to check, but the playing next dialog didn't appear.

**Comment by joezito129** [comment] 2023-02-05 00:02
in playing_next.py try changing line 81 to:
if actionID in [92, 10]:

I think you are clicking on the screen when skipping forward which will close the dialog.

**Comment by Gujal00** [comment] 2023-02-05 01:48
The Next up dialog doesnt work correctly if you are using widgets as already reported in #29 . If you are playing from menus within the addon then it does show corrcectly as below
![screenshot00000](https://user-images.githubusercontent.com/17394059/216797373-f1131959-997c-4d6d-8fda-8a706194baed.png)

**Comment by ShibajiCh** [comment] 2023-02-05 05:54
Hi @Goldenfreddy0703,

I'm playing the video from within the Otaku addon and not from widget. I changed the line 83 (not 81) in playing_next.py and checked. I also played the entire video from start to finish without forwarding or rewinding. However, still I'm not seeing the Playing Next Dialog pop-up anymore. Also, once the video stops playing, the next video doesn't auto play. Nevertheless, the already played video gets marked as watched in Anilist. This started happening after the recent updates. Earlier everything used to work fine. Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 06:02
Tomorrow I will look at it but let me test just incase, can you tell me the anime and did you go to the watchlist?

**Comment by ShibajiCh** [comment] 2023-02-05 06:08
> Tomorrow I will look at it but let me test just incase, can you tell me the anime and did you go to the watchlist?

Hi @Goldenfreddy0703,

I played the videos from both inside Anilist Next Up as well as from within any TV Show Episodes list. I tested using several TV Shows. One of them is "Attack on Titan". Kindly check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-05 09:17
Hi @Goldenfreddy0703,

Did you get time to test this issue? Are you also facing the same problem?

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment] 2023-02-05 16:22
Hi @Goldenfreddy0703,

Once you test this issue and if you face the same problem then could you please let me know if I should create a new ticket for this or if you're going to reopen this ticket only?

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 16:38
Ummm ok well do the troubleshooting steps again if you don't mind especially then try again and send me another log.

**Comment by ShibajiCh** [comment] 2023-02-05 16:57
> Ummm ok well do the troubleshooting steps again if you don't mind especially then try again and send me another log.

Hi @Goldenfreddy0703,

I did the troubleshooting steps again but the issue is still there. Neither I'm seeing the Playing Next Dialog not the Next Episode plays at the end. Please find attached my updated log:

https://paste.kodi.tv/xiholuveyi

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:00
Your using your vpn right????

**Comment by ShibajiCh** [comment] 2023-02-05 17:01
> Your using your vpn right????

Yes, I'm using the VPN.

**Comment by ShibajiCh** [comment] 2023-02-05 17:10
Hi @Goldenfreddy0703,

I think the issue is here:

info <general>: [plugin.video.themoviedb.helper]
                                                   CACHE: Closed database_v6_TraktAPI.db_simplecache
2023-02-05 22:20:58.383 T:19569   error <general>: GetItemsForPlayList: Unable to get playlist items for plugin://plugin.video.otaku/play/16498/3/
2023-02-05 22:20:59.440 T:19569    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/get_sources.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 22:21:09.083 T:19569    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/source_select.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 22:21:10.734 T:19569    info <general>: Loading skin file: /storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/skins/Default/1080i/resolver.xml, load type: LOAD_ON_GUI_INIT
2023-02-05 22:21:14.588 T:31589   error <general>: EXCEPTION: array out of bound
2023-02-05 22:21:16.829 T:19569    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.otaku/play/16498/3/
2023-02-05 22:21:16.833 T:31681    info <general>: Creating InputStream
2023-02-05 22:21:16.911 T:31589   error <general>: EXCEPTION: array out of bound
2023-02-05 22:21:18.104 T:31681    info <general>: Creating Demuxer
2023-02-05 22:21:22.901 T:31681    info <general>: Opening stream: 0 source: 256
2023-02-05 22:21:22.901 T:31681    info <general>: Creating video codec with codec id: 173
2023-02-05 22:21:22.901 T:31681    info <general>: CBitstreamConverter::Open bitstream to annexb init
2023-02-05 22:21:22.901 T:31681    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.mp2.decoder
2023-02-05 22:21:22.902 T:31681    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.wma.decoder
2023-02-05 22:21:22.902 T:31681    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.h264.decode
2023-02-05 22:21:22.902 T:31681    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.DOVI.decode
2023-02-05 22:21:22.902 T:31681    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.Nvidia.h263.decode
2023-02-05 22:21:22.903 T:31681    info <general>:

**Comment by ShibajiCh** [comment] 2023-02-05 17:11
I think Otaku is not able to create the playlist, why might that be?

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:17
Ok im going to say this and im not trying to be rude but get a different vpn or fresh build of kodi at this point, Fix your Advanced Settings file, idk at this point. 

You have like 485 errors where its got to be your vpn at this point or advanced settings file. Idk what isp you have but its strict like your internet and honestly idk what to do at this point. 
![image](https://user-images.githubusercontent.com/62456796/216833901-9552a024-4d73-4752-b68f-e81ded9177d7.png)

This log file is showing errors related to the Kodi media player software. The error messages are indicating that there are problems with loading images or media resources, either because the files cannot be found or because they cannot be opened. The log also shows that there are issues with retrieving directories or playlist items from certain plugins, such as the "otaku" video plugin. Additionally, there are warnings about deprecated usage of video properties and some other control-related errors.

**Comment by ShibajiCh** [comment] 2023-02-05 17:20
@Goldenfreddy0703,

Okay, I played the video without VPN as well using non-Nyaa links but still it's not showing the Playing Next Dialog. Is the Playing Next Dialog working for you fine? I'm asking this because it was working for me perfectly even few days back on the same build. Something happened during the last few updates which stopped it from appearing.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:21
Ok, personally i think all these errors are defiantly related to your advanced settings xml you have or it could be the kodi build itself that you are using. 
 
 The log shows that there were several errors encountered while the program was running.

    "Image error: Could not open cached image --> [Errno 2] No such file or directory" - This error is indicating that the program is trying to access an image file at a specific location, but the file could not be found.

    "DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/*" - This error is indicating that the program is trying to load an image, but the image file could not be found or loaded.

    "GetDirectory - Error getting -" - This error is indicating that the program is trying to access a directory, but it could not be found or accessed.

    "GetDirectory - Error getting plugin://" - This error is indicating that the program is trying to access a plugin directory, but it could not be found or accessed.

    "CGUIMediaWindow::GetDirectory(...)" - This error is indicating that the program is trying to access a media window, but it could not be found or accessed.

    "Control 501 in window 10025 has been asked to focus, but it can't" - This error is indicating that the program is trying to set the focus on a specific control, but it cannot be done.

    "Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions." - This warning message is indicating that a certain way of setting video properties is being deprecated and may not work in future releases.

    "GetItemsForPlayList: Unable to get playlist items for plugin://" - This error is indicating that the program is trying to access a playlist item, but it could not be found or accessed.

These errors and warnings could be caused by a variety of factors, such as missing or corrupted files, incorrect file paths, or problems with plugins.

**Comment by ShibajiCh** [comment] 2023-02-05 17:22
@Goldenfreddy0703,

Not sure why there are so many errors suddenly but everything else is working fine apart from the Playing Next Dialog.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:22
> Okay, I played the video without VPN as well using non-Nyaa links but still it's not showing the Playing Next Dialog. Is the Playing Next Dialog working for you fine? I'm asking this because it was working for me perfectly even few days back on the same build. Something happened during the last few updates which stopped it from appearing.

Everything has been working for me just fine and everything is straight forward, this is an issue on your end cause you are the only user that i have ever talked to who has these issues.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:23
> @Goldenfreddy0703,
> 
> Not sure why there are so many errors suddenly but everything else is working fine apart from the Playing Next Dialog.

Its either your advancesettings.xml or your build or your vpn.

**Comment by ShibajiCh** [comment] 2023-02-05 17:24
@Goldenfreddy0703,

In that case I won't bother you further. I can live without the Playing Next Dialog since moving forward I'll be using Otaku from the widgets, where the Playing Next Dialog doesn't work at present.

**Comment by ShibajiCh** [comment] 2023-02-05 17:24
,

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:24
![image](https://user-images.githubusercontent.com/62456796/216834715-512f58fc-41af-4503-a117-310826002224.png)
Look it can't even access fanart tv in this part of the log

**Comment by ShibajiCh** [comment] 2023-02-05 17:26
Fine @Goldenfreddy0703, but all artworks are appearing perfectly. Not sure what might be causing the issue.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:28
> In that case I won't bother you further. I can live without the Playing Next Dialog since moving forward I'll be using Otaku from the widgets, where the Playing Next Dialog doesn't work at present.

Listen im not trying to be rude of anything and i understand that you been having a ton of problems with your kodi, I think you should either download the official kodi, or see why your vpn has been having so many issues, or fix your advancedsettings.xml that you have those are my three options i recommend but at this point your kodi is very wack then any other user out there. 

 If you have a discord, contact me on discord and i can probably help you with those problems
 
 My Discord: The Steampunk Owl#3126

**Comment by ShibajiCh** [comment] 2023-02-05 17:33
> > In that case I won't bother you further. I can live without the Playing Next Dialog since moving forward I'll be using Otaku from the widgets, where the Playing Next Dialog doesn't work at present.
> 
> Listen im not trying to be rude of anything and i understand that you been having a ton of problems with your kodi, I think you should either download the official kodi, or see why your vpn has been having so many issues, or fix your advancedsettings.xml that you have, those are my three options i recommend but at this point your kodi is very wack then any other user out there.
> 
> If you have a discord, contact me on discord and i can probably help you with those problems
> 
> My Discord: The Steampunk Owl#3126

Hi @Goldenfreddy0703,

No problem. Thanks for all your help! I'll check further and get in touch with you.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:37
Anytime but i have looked carefully and if it helps, reinstall your inputstream adaptive, fix your permissions with your advanced settings.xml or delete it if you could and i thin that will fix most of your issues. Sense your on an nvidia shield, make sure to clear your kodi cache. 

If you can do all that then you will be golden i hope.

**Comment by ShibajiCh** [comment] 2023-02-05 17:41
> Anytime but i have looked carefully and if it helps, reinstall your inputstream adaptive, fix your permissions with your advanced settings.xml or delete it if you could and i think that will fix most of your issues. Sense your on an nvidia shield, make sure to clear your kodi cache.
> 
> If you can do all that then you will be golden i hope.

Sure @Goldenfreddy0703. 🙂👍🏻

Just for your information I was not getting the Playing Next Dialog in Seren addon as well before using my VPN, but now after using my VPN I'm even getting that perfectly. See below screenshot:

![IMG20230205230724](https://user-images.githubusercontent.com/65297828/216835832-8f305c98-358b-4346-9ea9-68386f57f9c1.jpg)

So I guess the issue with my VPN can be ruled out.

The thing that is bothering me is how I was getting the Playing Next Dialog in Otaku even 2-3 days back and what's causing the issue now. What might have changed? Let's see.

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:45
I should've ask you from the beginning but what type of vpn are you using?

**Comment by ShibajiCh** [comment] 2023-02-05 17:48
> I should've ask you from the beginning but what type of vpn are you using?

I'm using Nord VPN with Nordlynx protocol and USA or Singapore as server. The DNS are custom provided by Nord VPN.

**Comment by Goldenfreddy0703** [comment] 2023-02-05 17:53
Ohhhhhh......no wonder its been a hassle.....

Ok if i were me, i would cancel your debrid service or keep it if its real debrid but use premiumize.

premiumize is also a debrid service but its also a cloud storage service and vpn services for only 5$ a month if you pick the 12 month option. It will literally take care of everything for you and i think you should do it and get rid of your old vpn.

**Comment by ShibajiCh** [comment] 2023-02-05 18:04
> Ohhhhhh......no wonder its been a hassle.....
> 
> Ok if i were me, i would cancel your debrid service or keep it if its real debrid but use premiumize.
> 
> premiumize is also a debrid service but its also a cloud storage service and vpn service for only 5$ a month if you pick the 12 month option. It will literally take care of everything for you and i think you should do it and get rid of your old vpn.
> 
> https://www.premiumize.me/premium

Fine @Goldenfreddy0703, I'll check. Thank you!

**Comment by Goldenfreddy0703** [comment] 2023-02-05 18:05
> > I should've ask you from the beginning but what type of vpn are you using?
> 
> I'm using Nord VPN with Nordlynx protocol and USA or Singapore as server. The DNS are custom provided by Nord VPN.

Hey sense you have Nord VPN, i did some research on it and it could be due to a setting called Threat Protection. If you disabled that, maybe your kodi can work again.

**Comment by ShibajiCh** [comment] 2023-02-05 18:18
Hi @Goldenfreddy0703,

Threat protection is already disabled and like I said earlier that I even tested without my VPN and still the Playing Next Dialog is not appearing. This issue has started happening since last 2-3 dates after the recent updates. Earlier everything was working fine. Thank you so much for your prompt replies and your help!

Thanks and Regards,
ShibajiCh.

**Comment by Goldenfreddy0703** [comment] 2023-02-24 04:55
Hey @AakashC2020 , sorry for bothering you but i need you to do some testing for me. Last time, you had a problem with audio stream and some of it was on me. Could you test this new release of Otaku again, I made some audio improvements but i wanna make sure they are working so mess with preferred audio stream settings when you have time, thank you.

**Comment by AakashC2020** [comment] 2023-02-24 06:09
Hi @Goldenfreddy0703,

Sure. I'll check and let you know.

**Comment by AakashC2020** [comment] 2023-02-24 14:50
> Hey @AakashC2020 , sorry for bothering you but i need you to do some testing for me. Last time, you had a problem with audio stream and some of it was on me. Could you test this new release of Otaku again, I made some audio improvements but i wanna make sure they are working so mess with preferred audio stream settings when you have time, thank you.

Hi @Goldenfreddy0703,

I've tested the audio settings with all types of options and they are working perfectly. Thank you!
